In [1]:
#Opened with --pylab flag
#Need to create code to analyze piot data
import pandas as pd
import numpy as np
from scipy import io
import os
import glob

In [37]:
## Laptop
#filepath = '/Users/frankkanayet/Dropbox/NLineExperiment/PilotData'
#filepath = '/Users/frankkanayet/Dropbox/NLineExperiment/PilotData/test3s'
filepath = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data'

## Desktop
#filepath = '/Users/frankanayet/Dropbox/NLineExperiment/Data'
os.chdir(filepath)

In [38]:
#print 'Pandas version ' + pd.__version__

In [39]:
filenames = glob.glob('Nline_*.mat')
print filenames
#index to isolate subj numbers
data_dict = {}
for i in filenames:
    id1 = filenames[0].find('_') + 1
    id2 = filenames[0].find('-')
    sub_nbr = i[id1:id2]
    sub_name = i
    s_id = 's_'+sub_nbr
    data_dict[s_id] = io.loadmat(sub_name)

#sub_name = filenames[0] #This will be changed to a loop for all subjects later
#mat = io.loadmat(sub_name)
data_dict.keys()

['Nline_02001-Mar1615.mat', 'Nline_02002-Mar1915.mat', 'Nline_02003-Mar2015a.mat', 'Nline_02004-Mar2315a.mat', 'Nline_02005-Mar2315a.mat', 'Nline_02006-Mar2315a.mat', 'Nline_02007-Mar2415a.mat', 'Nline_02009-Mar2615a.mat', 'Nline_02010-Mar2615a.mat', 'Nline_02011-Mar2615a.mat', 'Nline_02012-Apr0215a.mat', 'Nline_02014-Apr0315a.mat']


['s_02009',
 's_02003',
 's_02002',
 's_02001',
 's_02007',
 's_02006',
 's_02005',
 's_02004',
 's_02014',
 's_02010',
 's_02011',
 's_02012']

In [40]:
sub_ex = data_dict.keys()[0]

In [41]:
#data_dict['s_00011']['p']

In [42]:
#for i in data_dict:
#    data_dict[i].pop('__header__')
#    data_dict[i].pop('__version__')
#    data_dict[i].pop('__globals__')
#data_dict['s_00011'].keys()

In [43]:
## The indexes of zeros are as follows [0][0][x][y][z][0] The x y z are the 3 dimensions of the data 3d matrix the zeros are padding
data_dict[sub_ex]['p']['NlineResults'][0][0][0][5][0][0]
len(data_dict[sub_ex]['p']['NlineResults'][0][0][:])

49

In [44]:
data_dict[sub_ex]['p'].dtype.names

('ramp_up',
 'Mean_ITI',
 'Mean_hold',
 'decision',
 'consider',
 'runs',
 'nStim',
 'ntasks',
 'tasks',
 'trialSecs',
 'lineLength',
 'speed',
 'run_order',
 'NlineResults',
 'time_Runs',
 'task_transition',
 'start_Nline',
 'finish_Nline')

In [45]:
cons_time = data_dict[sub_ex]['p']['consider'][0][0][0][0]
dec_time = data_dict[sub_ex]['p']['decision'][0][0][0][0]

In [46]:
new_dat = {}
#new_df = {}
for s in data_dict:
    tasks = ['NlineResults']
    new_dat[s]={}
    #new_df[s] = {}
    for task in tasks:
        dat = data_dict[s]['p'][task]
        num_fields = len(data_dict[s]['p'][task][0][0][0])
        dat_names = []
        for k in range(0,num_fields):
            dat_names.append(dat[0][0][0][k][0][0])
        new_dat[s][task] = {}
        runs = data_dict[s]['p']['runs'][0][0][0][0]
        for run in range(0,runs):
            run_name = 'Run_'+str(run)
            new_dat[s][task][run_name] = {}
            for i in range(0,len(dat_names)):
                new_dat[s][task][run_name][dat_names[i]] = []
                for j in range(0,len(dat[0][0][:])-1):
                    if dat_names[i] == 'catch_probe':
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run])
                    elif dat_names[i] == 'Probe':
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run][0])
                    else:
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run][0][0])
#legible access to the data
Nline = 'NlineResults' #numberline

In [47]:
new_dat[sub_ex]['NlineResults']['Run_1'].keys()

[u'Slow',
 u'Line_pct',
 u'iti',
 u'TestX',
 u'ITI_onset_real',
 u'consider_onset_real',
 u'ITI_onset',
 u'RT',
 u'hold',
 u'decision_end',
 u'decision_onset_real',
 u'RTHold',
 u'decision_end_real',
 u'Correct',
 u'Wrong',
 u'BadPress',
 u'consider_onset',
 u'Response',
 u'Task',
 u'Trial',
 u'Points',
 u'Error',
 u'catch',
 u'mouse_pos',
 u'Block',
 u'catch_probe',
 u'Probe',
 u'hold_onset',
 u'Move',
 u'decision_onset',
 u'hold_onset_real',
 u'Click']

In [48]:
new_dat[sub_ex]['NlineResults']['Run_1']['Probe']

[u'he',
 u'my',
 u'it',
 u'me',
 u'as',
 u'ox',
 u'am',
 u'we',
 u'do',
 u'so',
 u'of',
 u'or',
 u'if',
 u'be',
 u'by',
 u'is',
 array([-94], dtype=int16),
 array([14], dtype=uint8),
 array([-34], dtype=int16),
 array([-44], dtype=int16),
 array([-86], dtype=int16),
 array([30], dtype=uint8),
 array([48], dtype=uint8),
 array([-10], dtype=int16),
 array([70], dtype=uint8),
 array([-28], dtype=int16),
 array([20], dtype=uint8),
 array([-58], dtype=int16),
 array([80], dtype=uint8),
 array([54], dtype=uint8),
 array([96], dtype=uint8),
 array([-78], dtype=int16),
 array([33], dtype=uint8),
 array([65], dtype=uint8),
 array([3], dtype=uint8),
 array([57], dtype=uint8),
 array([45], dtype=uint8),
 array([28], dtype=uint8),
 array([90], dtype=uint8),
 array([7], dtype=uint8),
 array([77], dtype=uint8),
 array([21], dtype=uint8),
 array([36], dtype=uint8),
 array([98], dtype=uint8),
 array([74], dtype=uint8),
 array([11], dtype=uint8),
 array([85], dtype=uint8),
 array([60], dtype=uint8)]

In [49]:
new_dat[sub_ex]['NlineResults']['Run_1']['catch_probe']

[array([u'he'], 
       dtype='<U2'), array([u'my'], 
       dtype='<U2'), array([u'it'], 
       dtype='<U2'), array([u'me'], 
       dtype='<U2'), array([u'of'], 
       dtype='<U2'), array([u'my'], 
       dtype='<U2'), array([u'am'], 
       dtype='<U2'), array([u'we'], 
       dtype='<U2'), array([u'do'], 
       dtype='<U2'), array([u'so'], 
       dtype='<U2'), array([u'of'], 
       dtype='<U2'), array([u'or'], 
       dtype='<U2'), array([u'if'], 
       dtype='<U2'), array([u'or'], 
       dtype='<U2'), array([u'by'], 
       dtype='<U2'), array([u'be'], 
       dtype='<U2'), array([], shape=(0, 0), dtype=uint8), array([], shape=(0, 0), dtype=uint8), array([], shape=(0, 0), dtype=uint8), array([], shape=(0, 0), dtype=uint8), array([], shape=(0, 0), dtype=uint8), array([], shape=(0, 0), dtype=uint8), array([], shape=(0, 0), dtype=uint8), array([], shape=(0, 0), dtype=uint8), array([], shape=(0, 0), dtype=uint8), array([], shape=(0, 0), dtype=uint8), array([], shape=(0, 0), dty

In [50]:
subj = data_dict.keys()
tasks = [Nline]
tuples = []
rows = len(data_dict[sub_ex]['p'][Nline][0][0][:])-1
for s in subj:
    runs = new_dat[s]['NlineResults'].keys()
    for run in runs:
        for i in range(0,rows):
            tuples.append((s, run, i))
len(tuples)
#iterables = [subj,tasks,runs]
indexes = pd.MultiIndex.from_tuples(tuples, names=['Subj', 'Run', 'Trial'])
nline_cols = len(new_dat[sub_ex][Nline]['Run_0'].keys())

In [51]:
indexes[90]

('s_02009', 'Run_2', 42)

In [52]:
indexes[1][1]

'Run_3'

In [53]:
varnames = new_dat[sub_ex][Nline]['Run_0'].keys()
varnames[24]

u'Block'

In [54]:
len(indexes)

2112

In [55]:
# Code empty cells of probes and catch_probes as Nan
Dic_list = []
probes = ['catch_probe']
for data in indexes:
    temp_dict = {}
    for var in varnames:
        if var == probes[0]:
            if len(new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]]) == 0:
                new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]] = np.array([np.nan])
            temp_dict[var] = new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]][0]
        else:
            temp_dict[var] = new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]]
    Dic_list.append(temp_dict)

In [56]:
#Create dataframe
nline_df = pd.DataFrame(Dic_list, index=indexes)
sum(nline_df.loc[sub_ex].loc['Run_0'].iloc[0:48]['catch'])

12

In [57]:
nline_df.loc[sub_ex].loc['Run_0'].iloc[0:10]['Error']

Trial
0       -0.023744
1       -0.025507
2        0.000000
3        0.000000
4       -0.027313
5        0.001938
6       -0.046035
7        0.000000
8        0.070881
9        0.026916
Name: Error, dtype: float64

In [58]:
nline_df.index.names = ['Subject', 'Run', 'Trial']
nline_df.index.names

FrozenList([u'Subject', u'Run', u'Trial'])

In [59]:
test = nline_df['Probe']
for i in range(0,len(test)):
    test[i] = np.ravel(test[i])
    test[i] = test[i][0]
nline_df['Probe'] = test
nline_df['Probe']

/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


Subject  Run    Trial
s_02009  Run_3  0        -44
                1         80
                2        -10
                3         14
                4         48
                5        -86
                6         54
                7        -94
                8        -58
                9         30
                10       -34
                11        70
                12       -78
                13        20
                14       -28
...
s_02012  Run_0  33       21
                34       65
                35       45
                36       33
                37       28
                38       90
                39       60
                40        3
                41       74
                42       57
                43       36
                44       11
                45       98
                46       85
                47       77
Name: Probe, Length: 2112, dtype: object

### Create Stim Labels

In [27]:
#now nline
#nline_df['Num'] = nline_df['Num'].map('{:.0f}'.format)
#nline_df['Denom'] = nline_df['Denom'].map('{:.0f}'.format)
#nline_df['Stim'] = nline_df['Num']+'/'+nline_df['Denom']
#nline_df['Stim']

In [60]:
nline_df.columns

Index([u'BadPress', u'Block', u'Click', u'Correct', u'Error', u'ITI_onset', u'ITI_onset_real', u'Line_pct', u'Move', u'Points', u'Probe', u'RT', u'RTHold', u'Response', u'Slow', u'Task', u'TestX', u'Trial', u'Wrong', u'catch', u'catch_probe', u'consider_onset', u'consider_onset_real', u'decision_end', u'decision_end_real', u'decision_onset', u'decision_onset_real', u'hold', u'hold_onset', u'hold_onset_real', u'iti', u'mouse_pos'], dtype='object')

In [103]:
#Make task as string
nline_df['Task'] = nline_df['Task'].astype(str)
nline_df['Task'][nline_df['Task']=='1'] = 'Pos'
nline_df['Task'][nline_df['Task']=='2'] = 'Neg'
nline_df['Task'][nline_df['Task']=='3'] = 'Word'
nline_df['Task'].iloc[16]

/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


'Word'

# Create Onset Files

In [113]:
import string
tasks = nline_df.groupby('Task')
labels = tasks.indices.keys()
cons_onset = {}
dec_onset = {}
dec_ctch_onset = {}
# Breaks always happen at the same time in the sequence
break_onset = [[190, 6, 1],[388, 6, 1]]
for s in nline_df.index.levels[0]:
    print s
    cons_onset[s] = {}
    dec_onset[s] = {}
    dec_ctch_onset[s] = {}
    for r in nline_df.index.levels[1]:
        #print r
        ctch = nline_df.loc[s].loc[r]['catch']
        dec_ctch_tmp = nline_df.loc[s].loc[r]['decision_onset_real'] - 16
        dec_ctch_tmp = dec_ctch_tmp[ctch==1]
        dec_ctch_onset[s][r] = pd.DataFrame.from_items([('time',dec_ctch_tmp[dec_ctch_tmp>=0]),('duration',dec_time),('val',1)])
        cons_onset[s][r] = {}
        dec_onset[s][r] = {}
        for lab in labels:
            #print lab
            Task = nline_df.loc[s].loc[r]['Task']
            dec_tmp = nline_df.loc[s].loc[r]['decision_onset_real'] - 16
            dec_tmp = dec_tmp[ctch==0]
            dec_tmp = dec_tmp[Task==lab]
            dec_onset[s][r][lab] = pd.DataFrame.from_items([('time',dec_tmp[dec_tmp>=0]),('duration',dec_time),('val',1)])
            cons_tmp = nline_df.loc[s].loc[r]['consider_onset_real'] - 16
            cons_tmp = cons_tmp[Task==lab]
            cons_onset[s][r][lab] = pd.DataFrame.from_items([('time',cons_tmp[cons_tmp>=0]),('duration',cons_time),('val',1)])

s_02001
s_02002
s_02003
s_02004
s_02005
s_02006
s_02007
s_02009
s_02010
s_02011
s_02012
s_02014


## Save Files

In [119]:
tasks = {'Pos': [cons_onset,dec_onset], 'Neg': [cons_onset,dec_onset],
         'Word': [cons_onset,dec_onset]}
for s in nline_df.index.levels[0]:
    print s
    #Laptop
    path = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data/OnsetFiles'
    path = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data/OnsetFiles/'+s+'/'
    os.makedirs(path)
    for r in nline_df.index.levels[1]:
        print r
        dec_ctch_filename = s+'_'+r+'DEC_CTCH'+'_'+'.txt'
        dec_pathfile = path+dec_ctch_filename
        dec_ctch_onset[s][r].to_csv(dec_pathfile, sep='\t', header=False, index=False)
        for task in tasks.keys():
            print task
            dec_filename = s+'_'+task+'_'+r+'_'+'DEC'+'.txt'
            cons_filename = s+'_'+task+'_'+r+'_'+'CONS'+'.txt'
            dec_pathfile = path+dec_filename
            cons_pathfile = path+cons_filename
            tasks[task][0][s][r][task].to_csv(cons_pathfile, sep='\t', header=False, index=False)
            tasks[task][1][s][r][task].to_csv(dec_pathfile, sep='\t', header=False, index=False)

s_02001
Run_0
Neg
Word
Pos
Run_1
Neg
Word
Pos
Run_2
Neg
Word
Pos
Run_3
Neg
Word
Pos
s_02002
Run_0
Neg
Word
Pos
Run_1
Neg
Word
Pos
Run_2
Neg
Word
Pos
Run_3
Neg
Word
Pos
s_02003
Run_0
Neg
Word
Pos
Run_1
Neg
Word
Pos
Run_2
Neg
Word
Pos
Run_3
Neg
Word
Pos
s_02004
Run_0
Neg
Word
Pos
Run_1
Neg
Word
Pos
Run_2
Neg
Word
Pos
Run_3
Neg
Word
Pos
s_02005
Run_0
Neg
Word
Pos
Run_1
Neg
Word
Pos
Run_2
Neg
Word
Pos
Run_3
Neg
Word
Pos
s_02006
Run_0
Neg
Word
Pos
Run_1
Neg
Word
Pos
Run_2
Neg
Word
Pos
Run_3
Neg
Word
Pos
s_02007
Run_0
Neg
Word
Pos
Run_1
Neg
Word
Pos
Run_2
Neg
Word
Pos
Run_3
Neg
Word
Pos
s_02009
Run_0
Neg
Word
Pos
Run_1
Neg
Word
Pos
Run_2
Neg
Word
Pos
Run_3
Neg
Word
Pos
s_02010
Run_0
Neg
Word
Pos
Run_1
Neg
Word
Pos
Run_2
Neg
Word
Pos
Run_3
Neg
Word
Pos
s_02011
Run_0
Neg
Word
Pos
Run_1
Neg
Word
Pos
Run_2
Neg
Word
Pos
Run_3
Neg
Word
Pos
s_02012
Run_0
Neg
Word
Pos
Run_1
Neg
Word
Pos
Run_2
Neg
Word
Pos
Run_3
Neg
Word
Pos
s_02014
Run_0
Neg
Word
Pos
Run_1
Neg
Word
Pos
Run_2
Neg
Word
Pos
Run_3
Neg
W

In [124]:
#Save Break onset file
path = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data/OnsetFiles/'
#Laptop
break_onset = pd.DataFrame.from_items([('time',[190, 388]),('duration',[6,6]),('val',[1,1])])
break_filename = 'Break_onsets.txt'
break_pathfile = path+break_filename
break_onset.to_csv(break_pathfile, sep='\t', header=False, index=False)