## Not using RTs to modulate duration or decision and including Miss trials into the decision regressors. Dec = 3s, Cons = cons + minHold

In [1]:
#Opened with --pylab flag
#Need to create code to analyze piot data
import pandas as pd
import numpy as np
from scipy import io
import os
import glob

In [2]:
## Laptop
#filepath = '/Users/frankkanayet/Dropbox/NLineExperiment/PilotData'
#filepath = '/Users/frankkanayet/Dropbox/NLineExperiment/PilotData/test3s'
#filepath = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data'

## Desktop
#filepath = '/Users/frankanayet/Dropbox/NLineExperiment/Data'
filepath = '/Users/frankanayet/Google Drive/NLineData/Beh_Data'
os.chdir(filepath)

In [3]:
print 'Pandas version ' + pd.__version__

Pandas version 0.17.1


In [4]:
filenames = glob.glob('Nline_*.mat')
print filenames
#index to isolate subj numbers
data_dict = {}
for i in filenames:
    id1 = filenames[0].find('_') + 1
    id2 = filenames[0].find('-')
    sub_nbr = i[id1:id2]
    sub_name = i
    s_id = 's_'+sub_nbr
    data_dict[s_id] = io.loadmat(sub_name)

#sub_name = filenames[0] #This will be changed to a loop for all subjects later
#mat = io.loadmat(sub_name)
data_dict.keys()

['Nline_02001-Mar1615.mat', 'Nline_02002-Mar1915.mat', 'Nline_02003-Mar2015a.mat', 'Nline_02004-Mar2315a.mat', 'Nline_02005-Mar2315a.mat', 'Nline_02006-Mar2315a.mat', 'Nline_02007-Mar2415a.mat', 'Nline_02009-Mar2615a.mat', 'Nline_02010-Mar2615a.mat', 'Nline_02011-Mar2615a.mat', 'Nline_02012-Apr0215a.mat', 'Nline_02014-Apr0315a.mat', 'Nline_02015Apr2715a.mat', 'Nline_02016-Apr2715a.mat', 'Nline_02017-Apr2815a.mat', 'Nline_02018-Apr2815a.mat', 'Nline_02019-Apr2915a.mat', 'Nline_02020-May1815a.mat', 'Nline_02021-May2515a.mat', 'Nline_02022-May2515a.mat', 'Nline_02023-May2715a.mat', 'Nline_02024-May2815a.mat', 'Nline_02027-Jun0115a.mat']


['s_02009',
 's_02003',
 's_02002',
 's_02001',
 's_02007',
 's_02006',
 's_02005',
 's_02004',
 's_02018',
 's_02019',
 's_02010',
 's_02011',
 's_02012',
 's_02014',
 's_02015',
 's_02016',
 's_02017',
 's_02024',
 's_02027',
 's_02021',
 's_02020',
 's_02023',
 's_02022']

In [5]:
sub_ex = data_dict.keys()[0]

In [6]:
#data_dict['s_00011']['p']

In [7]:
#for i in data_dict:
#    data_dict[i].pop('__header__')
#    data_dict[i].pop('__version__')
#    data_dict[i].pop('__globals__')
#data_dict['s_00011'].keys()

In [8]:
## The indexes of zeros are as follows [0][0][x][y][z][0] The x y z are the 3 dimensions of the data 3d matrix the zeros are padding
data_dict[sub_ex]['p']['NlineResults'][0][0][0][5][0][0]
len(data_dict[sub_ex]['p']['NlineResults'][0][0][:])

49

In [9]:
data_dict[sub_ex]['p'].dtype.names

('ramp_up',
 'Mean_ITI',
 'Mean_hold',
 'decision',
 'consider',
 'runs',
 'nStim',
 'ntasks',
 'tasks',
 'trialSecs',
 'lineLength',
 'speed',
 'run_order',
 'NlineResults',
 'time_Runs',
 'task_transition',
 'start_Nline',
 'finish_Nline')

In [10]:
cons_time = data_dict[sub_ex]['p']['consider'][0][0][0][0]
dec_time = data_dict[sub_ex]['p']['decision'][0][0][0][0]

In [11]:
new_dat = {}
#new_df = {}
for s in data_dict:
    tasks = ['NlineResults']
    new_dat[s]={}
    #new_df[s] = {}
    for task in tasks:
        dat = data_dict[s]['p'][task]
        num_fields = len(data_dict[s]['p'][task][0][0][0])
        dat_names = []
        for k in range(0,num_fields):
            dat_names.append(dat[0][0][0][k][0][0])
        new_dat[s][task] = {}
        runs = data_dict[s]['p']['runs'][0][0][0][0]
        for run in range(0,runs):
            run_name = 'run'+str(run+1)
            new_dat[s][task][run_name] = {}
            for i in range(0,len(dat_names)):
                new_dat[s][task][run_name][dat_names[i]] = []
                for j in range(0,len(dat[0][0][:])-1):
                    if dat_names[i] == 'catch_probe':
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run])
                    elif dat_names[i] == 'Probe':
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run][0])
                    else:
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run][0][0])
#legible access to the data
Nline = 'NlineResults' #numberline

In [12]:
new_dat[sub_ex]['NlineResults']['run1'].keys()

[u'Slow',
 u'Line_pct',
 u'iti',
 u'TestX',
 u'ITI_onset_real',
 u'consider_onset_real',
 u'ITI_onset',
 u'RT',
 u'hold',
 u'decision_end',
 u'decision_onset_real',
 u'RTHold',
 u'decision_end_real',
 u'Correct',
 u'Wrong',
 u'BadPress',
 u'consider_onset',
 u'Response',
 u'Task',
 u'Trial',
 u'Points',
 u'Error',
 u'catch',
 u'mouse_pos',
 u'Block',
 u'catch_probe',
 u'Probe',
 u'hold_onset',
 u'Move',
 u'decision_onset',
 u'hold_onset_real',
 u'Click']

In [13]:
new_dat[sub_ex]['NlineResults']['run1']['Probe']

[array([57], dtype=uint8),
 array([77], dtype=uint8),
 array([3], dtype=uint8),
 array([21], dtype=uint8),
 array([60], dtype=uint8),
 array([28], dtype=uint8),
 array([85], dtype=uint8),
 array([74], dtype=uint8),
 array([33], dtype=uint8),
 array([7], dtype=uint8),
 array([90], dtype=uint8),
 array([36], dtype=uint8),
 array([11], dtype=uint8),
 array([45], dtype=uint8),
 array([98], dtype=uint8),
 array([65], dtype=uint8),
 array([70], dtype=uint8),
 array([14], dtype=uint8),
 array([80], dtype=uint8),
 array([20], dtype=uint8),
 array([-58], dtype=int16),
 array([-94], dtype=int16),
 array([-86], dtype=int16),
 array([54], dtype=uint8),
 array([-44], dtype=int16),
 array([-78], dtype=int16),
 array([-10], dtype=int16),
 array([48], dtype=uint8),
 array([30], dtype=uint8),
 array([-28], dtype=int16),
 array([96], dtype=uint8),
 array([-34], dtype=int16),
 u'of',
 u'is',
 u'be',
 u'me',
 u'it',
 u'as',
 u'my',
 u'so',
 u'we',
 u'or',
 u'ox',
 u'by',
 u'am',
 u'he',
 u'do',
 u'if']

In [14]:
new_dat[sub_ex]['NlineResults'].keys()

['run1', 'run3', 'run2', 'run4']

In [15]:
new_dat[sub_ex]['NlineResults']['run1']['catch_probe']

[array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), 

In [16]:
subj = data_dict.keys()
tasks = [Nline]
tuples = []
rows = len(data_dict[sub_ex]['p'][Nline][0][0][:])-1
for s in subj:
    runs = new_dat[s]['NlineResults'].keys()
    for run in runs:
        for i in range(0,rows):
            tuples.append((s, run, i))
len(tuples)
#iterables = [subj,tasks,runs]
indexes = pd.MultiIndex.from_tuples(tuples, names=['Subj', 'Run', 'Trial'])
nline_cols = len(new_dat[sub_ex][Nline]['run1'].keys())

In [17]:
indexes[590]

('s_02007', 'run1', 14)

In [18]:
indexes[1][1]

'run1'

In [19]:
varnames = new_dat[sub_ex][Nline]['run1'].keys()
varnames[24]

u'Block'

In [20]:
len(indexes)

4224

In [21]:
# Code empty cells of probes and catch_probes as Nan
Dic_list = []
probes = ['catch_probe']
for data in indexes:
    temp_dict = {}
    for var in varnames:
        if var == probes[0]:
            if len(new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]]) == 0:
                new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]] = np.array([np.nan])
            temp_dict[var] = new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]][0]
        else:
            temp_dict[var] = new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]]
    Dic_list.append(temp_dict)

In [22]:
#Create dataframe
nline_df = pd.DataFrame(Dic_list, index=indexes)
sum(nline_df.loc[sub_ex].loc['run1'].iloc[0:48]['catch'])

12

In [23]:
nline_df.loc[sub_ex].loc['run1'].iloc[0:10]['Error']

Trial
0   -0.023744
1   -0.025507
2    0.000000
3    0.000000
4   -0.027313
5    0.001938
6   -0.046035
7    0.000000
8    0.070881
9    0.026916
Name: Error, dtype: float64

In [24]:
nline_df.index.names = ['Subject', 'Run', 'Trial']
nline_df.index.names

FrozenList([u'Subject', u'Run', u'Trial'])

In [25]:
test = nline_df['Probe']
for i in range(0,len(test)):
    test[i] = np.ravel(test[i])
    test[i] = test[i][0]
nline_df['Probe'] = test
nline_df['Probe']

/Users/frankanayet/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/frankanayet/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


Subject  Run   Trial
s_02009  run1  0         57
               1         77
               2          3
               3         21
               4         60
               5         28
               6         85
               7         74
               8         33
               9          7
               10        90
               11        36
               12        11
               13        45
               14        98
               15        65
               16        70
               17        14
               18        80
               19        20
               20       -58
               21       -94
               22       -86
               23        54
               24       -44
               25       -78
               26       -10
               27        48
               28        30
               29       -28
                       ... 
s_02022  run4  18        or
               19        my
               20        of
               21        we

### Create Stim Labels

In [26]:
#now nline
#nline_df['Num'] = nline_df['Num'].map('{:.0f}'.format)
#nline_df['Denom'] = nline_df['Denom'].map('{:.0f}'.format)
#nline_df['Stim'] = nline_df['Num']+'/'+nline_df['Denom']
#nline_df['Stim']

In [27]:
nline_df.columns

Index([u'BadPress', u'Block', u'Click', u'Correct', u'Error', u'ITI_onset',
       u'ITI_onset_real', u'Line_pct', u'Move', u'Points', u'Probe', u'RT',
       u'RTHold', u'Response', u'Slow', u'Task', u'TestX', u'Trial', u'Wrong',
       u'catch', u'catch_probe', u'consider_onset', u'consider_onset_real',
       u'decision_end', u'decision_end_real', u'decision_onset',
       u'decision_onset_real', u'hold', u'hold_onset', u'hold_onset_real',
       u'iti', u'mouse_pos'],
      dtype='object')

In [28]:
#Make task as string
nline_df['Task'] = nline_df['Task'].astype(str)
nline_df['Task'][nline_df['Task']=='1'] = 'Pos'
nline_df['Task'][nline_df['Task']=='2'] = 'Neg'
nline_df['Task'][nline_df['Task']=='3'] = 'Word'
nline_df['Task'].iloc[16]

/Users/frankanayet/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/frankanayet/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/frankanayet/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


'Neg'

In [29]:
nline_df['Dist0'] = abs(nline_df['Line_pct'] - 0)
nline_df['Dist100'] = abs(nline_df['Line_pct'] - 1)
nline_df['Dist50'] = abs(nline_df['Line_pct'] - 0.5)
nline_df['LandmarkDist'] = nline_df[['Dist0','Dist100','Dist50']].min(axis=1) 
nline_df['LandmarkDist']

Subject  Run   Trial
s_02009  run1  0        0.07
               1        0.23
               2        0.03
               3        0.21
               4        0.10
               5        0.22
               6        0.15
               7        0.24
               8        0.17
               9        0.07
               10       0.10
               11       0.14
               12       0.11
               13       0.05
               14       0.02
               15       0.15
               16       0.15
               17       0.07
               18       0.10
               19       0.10
               20       0.21
               21       0.03
               22       0.07
               23       0.23
               24       0.22
               25       0.11
               26       0.05
               27       0.24
               28       0.15
               29       0.14
                        ... 
s_02022  run4  18       0.15
               19       0.03
               20     

##Get means for demeaning

In [30]:
nline_df['LandmarkDist'] = np.round(nline_df['LandmarkDist'],2)
uniquevals = nline_df.loc['s_02007'].loc['run1']['LandmarkDist'].unique()
landmark_mean = uniquevals.mean()

In [31]:
nline_df['Dist50'] = np.round(nline_df['Dist50'],2)
uniquevals50 = nline_df.loc['s_02007'].loc['run1']['Dist50'].unique()
dist50_mean = uniquevals50.mean()

In [32]:
nline_df['Dist0'] = np.round(nline_df['Dist0'],2)
uniquevals0 = nline_df.loc['s_02007'].loc['run1']['Dist0'].unique()
dist0_mean = uniquevals0.mean()

In [33]:
dist0_mean

0.49375000000000002

# Create Onset Files

In [34]:
nline_df['Missed'] = 0

In [35]:
nline_df['Missed'][(nline_df.catch < 1) & (nline_df.Error == 1)] = 1

/Users/frankanayet/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [40]:
import string
tasks = nline_df.groupby('Task')
labels = tasks.indices.keys()
phase = ['cons', 'dec', 'dec_ctch']
vals = ['int','zero','mid','land']

offset = 18
big_dict = {}

# Breaks always happen at the same time in the sequence
break_onset = [[190, 6, 1],[388, 6, 1]]
for s in nline_df.index.levels[0]:
    print s
    big_dict[s] = {}
    for r in nline_df.index.levels[1]:
        #print r
        big_dict[s][r] = {}
        
        ctch = nline_df.loc[s].loc[r]['catch']
        
        problem_con = nline_df.loc[s].loc[r]['consider_onset_real'] - nline_df.loc[s].loc[r]['consider_onset']
        problem_dec = nline_df.loc[s].loc[r]['decision_onset_real'] - nline_df.loc[s].loc[r]['decision_onset']
        prob_con_idx = problem_con > 0.5
        prob_dec_idx = problem_dec > 0.5
        
        if len(nline_df.loc[s].loc[r]['hold']) == 0:
            hold = 2.5
        else:
            hold = min(nline_df.loc[s].loc[r]['hold'])
            
        probe = nline_df.loc[s].loc[r]['Line_pct']
        cons_duration = hold + cons_time
        
        bad_trials_con = nline_df.loc[s].loc[r]['consider_onset'] - offset
        bad_trials_con = bad_trials_con[prob_con_idx==1]
        big_dict[s][r]['con_bad_trials'] = pd.DataFrame.from_items([('time',bad_trials_con[bad_trials_con>=0]),('duration',cons_duration),('val',1)])
        
        bad_trials_dec = nline_df.loc[s].loc[r]['decision_onset'] - offset
        bad_trials_dec = bad_trials_dec[prob_dec_idx==1]
        big_dict[s][r]['dec_bad_trials'] = pd.DataFrame.from_items([('time',bad_trials_dec[bad_trials_dec>=0]),('duration',dec_time),('val',1)])
      
        
        for lab in labels:
            #print lab
            big_dict[s][r][lab] = {}
            Task = nline_df.loc[s].loc[r]['Task']
            
            for ph in phase:
                if ph == 'dec':
                    big_dict[s][r][lab][ph] = {}
                    for val in vals:
                        big_dict[s][r][lab][ph][val] = {}
                        tmp_int = nline_df.loc[s].loc[r]['decision_onset_real'] - offset
                        tmp_int = tmp_int[ctch==0]
                        tmp_int = tmp_int[Task==lab]
                        tmp_int = tmp_int[prob_dec_idx==0]
                        
                        #create landmark values (demeaned)
                        landmark = nline_df.loc[s].loc[r]['LandmarkDist']
                        landmark = landmark[Task==lab] - landmark_mean
            
                        #create landmark values for distance from 50 (demeaned)
                        dist50 = nline_df.loc[s].loc[r]['Dist50']
                        dist50 = dist50[Task==lab] - dist50_mean
            
                        #create landmark distance from 0
                        dist0 = nline_df.loc[s].loc[r]['Dist0']
                        dist0 = dist0[Task==lab] - dist0_mean
                        
                        landmark = landmark[ctch==0]
                        dist50 = dist50[ctch==0]
                        dist0 = dist0[ctch==0]
                        
                        landmark = landmark[prob_dec_idx==0]
                        dist50 = dist50[prob_dec_idx==0]
                        dist0 = dist0[prob_dec_idx==0]
                        
                        val_dict = {'int':1,'zero':dist0,'mid':dist50,'land':landmark}
                        if val == 'int':
                            big_dict[s][r][lab][ph][val] = pd.DataFrame.from_items([('time',tmp_int[tmp_int>=0]),('duration',dec_time),('val',val_dict[val])])
                        else:
                            big_dict[s][r][lab][ph][val] = pd.DataFrame.from_items([('time',tmp_int[tmp_int>=0]),('duration',dec_time),('val',val_dict[val][tmp_int>=0])])
                        
                elif ph == 'dec_ctch':
                    big_dict[s][r][lab][ph] = {}
                    tmp_ctch = nline_df.loc[s].loc[r]['decision_onset_real'] - offset
                    tmp_ctch = tmp_ctch[ctch==1]
                    tmp_ctch = tmp_ctch[Task==lab]
                    tmp_ctch = tmp_ctch[prob_dec_idx==0]
                    big_dict[s][r][lab][ph] = pd.DataFrame.from_items([('time',tmp_ctch[tmp_ctch>=0]),('duration',dec_time),('val',1)])
                
                elif ph == 'cons':
                    big_dict[s][r][lab][ph] = {}
                    for val in vals:
                        big_dict[s][r][lab][ph][val] = {}
                        tmp_int = nline_df.loc[s].loc[r]['consider_onset_real'] - offset
                        tmp_int = tmp_int[Task==lab]
                        tmp_int = tmp_int[prob_con_idx==0]
                        
                        #create landmark values (demeaned)
                        landmark = nline_df.loc[s].loc[r]['LandmarkDist']
                        landmark = landmark[Task==lab] - landmark_mean
                        
                        #create landmark values for distance from 50 (demeaned)
                        dist50 = nline_df.loc[s].loc[r]['Dist50']
                        dist50 = dist50[Task==lab] - dist50_mean
                        
                        #create landmark distance from 0
                        dist0 = nline_df.loc[s].loc[r]['Dist0']
                        dist0 = dist0[Task==lab] - dist0_mean
                        landmark = landmark[prob_con_idx==0]
                        dist50 = dist50[prob_con_idx==0]
                        dist0 = dist0[prob_con_idx==0]
                        val_dict = {'int':1,'zero':dist0,'mid':dist50,'land':landmark}
                        if val == 'int':
                            big_dict[s][r][lab][ph][val] = pd.DataFrame.from_items([('time',tmp_int[tmp_int>=0]),('duration',cons_duration),('val',val_dict[val])])
                        else:
                            big_dict[s][r][lab][ph][val] = pd.DataFrame.from_items([('time',tmp_int[tmp_int>=0]),('duration',cons_duration),('val',val_dict[val][tmp_int>=0])])

s_02001
s_02002
s_02003
s_02004
s_02005
s_02006
s_02007
s_02009
s_02010
s_02011
s_02012
s_02014
s_02015
s_02016
s_02017
s_02018
s_02019
s_02020
s_02021
s_02022
s_02023
s_02024
s_02027


In [41]:
tmp_int

Trial
17    215.512966
18    228.504542
19    240.519548
20    256.514172
21    268.014369
22    280.002117
23    291.500969
24    301.521504
25    311.502928
26    325.015800
27    338.533004
29    363.023121
Name: decision_onset_real, dtype: float64

In [42]:
big_dict['s_02012']['run4']['Pos']

{'cons': {'int':              time  duration  val
  Trial                           
  0        0.505157         3    1
  1       13.503661         3    1
  2       24.004720         3    1
  3       37.503883         3    1
  4       49.503899         3    1
  5       65.502385         3    1
  6       78.504557         3    1
  7       89.504038         3    1
  8      102.502582         3    1
  9      116.003171         3    1
  10     126.502441         3    1
  11     137.004337         3    1
  12     146.504465         3    1
  13     157.003354         3    1
  14     167.504798         3    1
  15     179.501660         3    1,
  'land':              time  duration       val
  Trial                                
  0        0.505157         3  0.076154
  1       13.503661         3  0.016154
  2       24.004720         3 -0.033846
  3       37.503883         3 -0.103846
  4       49.503899         3  0.096154
  5       65.502385         3  0.106154
  6       78.504557       

## Save Files

In [43]:
#tasks = {'Pos': [cons_trial_int, dec_trial_int, cons_land, dec_land, cons_zero, dec_zero, cons_mid,
#                 dec_mid],
#         'Neg': [cons_trial_int, dec_trial_int, cons_land, dec_land, cons_zero, dec_zero, cons_mid,
#                 dec_mid],
#         'Word': [cons_trial_int, dec_trial_int, cons_land, dec_land, cons_zero, dec_zero, cons_mid,
#                 dec_mid]}

#taskname = ['cons_trial_int', 'dec_trial_int', 'cons_land', 'dec_land', 'cons_zero', 'dec_zero', 'cons_mid',
#            'dec_mid']
        
#runs = ['run1', 'run2', 'run3', 'run4']

for s in nline_df.index.levels[0]:
    print s
    #Laptop
    #path = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LandmarksFull'
    #path = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LandmarksFull/'+s+'/'
    #Desktop
    path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LandmarksFull4_'+str(offset)
    path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LandmarksFull4_'+str(offset)+'/'+s+'/'
    os.makedirs(path)
    for r in nline_df.index.levels[1]:
        print r
        dec_bad_filename = s+'_'+r+'_DEC_BAD'+'.txt'
        dec_bad_pathfile = path+dec_bad_filename
        big_dict[s][r]['dec_bad_trials'].to_csv(dec_bad_pathfile, sep='\t', header=False, index=False)
        
        con_bad_filename = s+'_'+r+'_CON_BAD'+'.txt'
        con_bad_pathfile = path+con_bad_filename
        big_dict[s][r]['con_bad_trials'].to_csv(con_bad_pathfile, sep='\t', header=False, index=False)
        
        del big_dict[s][r]['dec_bad_trials']
        del big_dict[s][r]['con_bad_trials']
        
        for lab in big_dict[s][r].keys():
            print lab
            for ph in big_dict[s][r][lab].keys():
                print ph
                if ph == 'dec_ctch':
                    filename = s+'_'+lab+'_'+r+'_'+ph+'.txt'
                    pathfile = path+filename
                    big_dict[s][r][lab][ph].to_csv(pathfile, sep='\t', header=False, index=False)
                else:
                    for val in big_dict[s][r][lab][ph].keys():
                        print val
                        filename = s+'_'+lab+'_'+r+'_'+ph+'_'+val+'.txt'
                        pathfile = path+filename
                        big_dict[s][r][lab][ph][val].to_csv(pathfile, sep='\t', header=False, index=False)

s_02001
run1
Neg
dec_ctch
cons
int
zero
land
mid
dec
int
zero
land
mid
Word
dec_ctch
cons
int
zero
land
mid
dec
int
zero
land
mid
Pos
dec_ctch
cons
int
zero
land
mid
dec
int
zero
land
mid
run2
Neg
dec_ctch
cons
int
zero
land
mid
dec
int
zero
land
mid
Word
dec_ctch
cons
int
zero
land
mid
dec
int
zero
land
mid
Pos
dec_ctch
cons
int
zero
land
mid
dec
int
zero
land
mid
run3
Neg
dec_ctch
cons
int
zero
land
mid
dec
int
zero
land
mid
Word
dec_ctch
cons
int
zero
land
mid
dec
int
zero
land
mid
Pos
dec_ctch
cons
int
zero
land
mid
dec
int
zero
land
mid
run4
Neg
dec_ctch
cons
int
zero
land
mid
dec
int
zero
land
mid
Word
dec_ctch
cons
int
zero
land
mid
dec
int
zero
land
mid
Pos
dec_ctch
cons
int
zero
land
mid
dec
int
zero
land
mid
s_02002
run1
Neg
dec_ctch
cons
int
zero
land
mid
dec
int
zero
land
mid
Word
dec_ctch
cons
int
zero
land
mid
dec
int
zero
land
mid
Pos
dec_ctch
cons
int
zero
land
mid
dec
int
zero
land
mid
run2
Neg
dec_ctch
cons
int
zero
land
mid
dec
int
zero
land
mid
Word
dec_ctch
cons
in

In [44]:
#Save Break onset file
path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LandmarksFull4_'+str(offset)
#Desktop
break_onset = pd.DataFrame.from_items([('time',[206-offset, 404-offset]),('duration',[6,6]),('val',[1,1])])
break_filename = 'Break_onsets.txt'
break_pathfile = path+'/'+break_filename
break_onset.to_csv(break_pathfile, sep='\t', header=False, index=False)

In [43]:
path

'/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LandmarksFull4_18'