In [1]:
#Opened with --pylab flag
#Need to create code to analyze piot data
import pandas as pd
import numpy as np
from scipy import io
import os
import glob

In [2]:
## Laptop
#filepath = '/Users/frankkanayet/Dropbox/NLineExperiment/PilotData'
#filepath = '/Users/frankkanayet/Dropbox/NLineExperiment/PilotData/test3s'
#filepath = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data'

## Desktop
#filepath = '/Users/frankanayet/Dropbox/NLineExperiment/Data'
filepath = '/Users/frankanayet/Google Drive/NLineData/Beh_Data'
os.chdir(filepath)

In [3]:
print 'Pandas version ' + pd.__version__

Pandas version 0.17.1


In [4]:
filenames = glob.glob('Nline_*.mat')
print filenames
#index to isolate subj numbers
data_dict = {}
for i in filenames:
    id1 = filenames[0].find('_') + 1
    id2 = filenames[0].find('-')
    sub_nbr = i[id1:id2]
    sub_name = i
    s_id = 's_'+sub_nbr
    data_dict[s_id] = io.loadmat(sub_name)

#sub_name = filenames[0] #This will be changed to a loop for all subjects later
#mat = io.loadmat(sub_name)
data_dict.keys()

['Nline_02001-Mar1615.mat', 'Nline_02018-Apr2815a.mat', 'Nline_02021-May2515a.mat', 'Nline_02016-Apr2715a.mat', 'Nline_02004-Mar2315a.mat', 'Nline_02007-Mar2415a.mat', 'Nline_02024-May2815a.mat', 'Nline_02012-Apr0215a.mat', 'Nline_02005-Mar2315a.mat', 'Nline_02019-Apr2915a.mat', 'Nline_02010-Mar2615a.mat', 'Nline_02006-Mar2315a.mat', 'Nline_02027-Jun0115a.mat', 'Nline_02011-Mar2615a.mat', 'Nline_02017-Apr2815a.mat', 'Nline_02009-Mar2615a.mat', 'Nline_02014-Apr0315a.mat', 'Nline_02020-May1815a.mat', 'Nline_02002-Mar1915.mat', 'Nline_02023-May2715a.mat', 'Nline_02003-Mar2015a.mat', 'Nline_02015-Apr2715a.mat', 'Nline_02022-May2515a.mat']


['s_02009',
 's_02003',
 's_02002',
 's_02001',
 's_02007',
 's_02006',
 's_02005',
 's_02004',
 's_02018',
 's_02019',
 's_02010',
 's_02011',
 's_02012',
 's_02014',
 's_02015',
 's_02016',
 's_02017',
 's_02024',
 's_02027',
 's_02021',
 's_02020',
 's_02023',
 's_02022']

In [6]:
sub_ex = data_dict.keys()[0]

In [7]:
#data_dict['s_00011']['p']

In [8]:
#for i in data_dict:
#    data_dict[i].pop('__header__')
#    data_dict[i].pop('__version__')
#    data_dict[i].pop('__globals__')
#data_dict['s_00011'].keys()

In [9]:
## The indexes of zeros are as follows [0][0][x][y][z][0] The x y z are the 3 dimensions of the data 3d matrix the zeros are padding
data_dict[sub_ex]['p']['NlineResults'][0][0][0][5][0][0]
len(data_dict[sub_ex]['p']['NlineResults'][0][0][:])

49

In [10]:
data_dict[sub_ex]['p'].dtype.names

('ramp_up',
 'Mean_ITI',
 'Mean_hold',
 'decision',
 'consider',
 'runs',
 'nStim',
 'ntasks',
 'tasks',
 'trialSecs',
 'lineLength',
 'speed',
 'run_order',
 'NlineResults',
 'time_Runs',
 'task_transition',
 'start_Nline',
 'finish_Nline')

In [11]:
cons_time = data_dict[sub_ex]['p']['consider'][0][0][0][0]
dec_time = data_dict[sub_ex]['p']['decision'][0][0][0][0]

In [12]:
new_dat = {}
#new_df = {}
for s in data_dict:
    tasks = ['NlineResults']
    new_dat[s]={}
    #new_df[s] = {}
    for task in tasks:
        dat = data_dict[s]['p'][task]
        num_fields = len(data_dict[s]['p'][task][0][0][0])
        dat_names = []
        for k in range(0,num_fields):
            dat_names.append(dat[0][0][0][k][0][0])
        new_dat[s][task] = {}
        runs = data_dict[s]['p']['runs'][0][0][0][0]
        for run in range(0,runs):
            run_name = 'run'+str(run+1)
            new_dat[s][task][run_name] = {}
            for i in range(0,len(dat_names)):
                new_dat[s][task][run_name][dat_names[i]] = []
                for j in range(0,len(dat[0][0][:])-1):
                    if dat_names[i] == 'catch_probe':
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run])
                    elif dat_names[i] == 'Probe':
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run][0])
                    else:
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run][0][0])
#legible access to the data
Nline = 'NlineResults' #numberline

In [13]:
new_dat[sub_ex]['NlineResults']['run1'].keys()

[u'Slow',
 u'Line_pct',
 u'iti',
 u'TestX',
 u'ITI_onset_real',
 u'consider_onset_real',
 u'ITI_onset',
 u'RT',
 u'hold',
 u'decision_end',
 u'decision_onset_real',
 u'RTHold',
 u'decision_end_real',
 u'Correct',
 u'Wrong',
 u'BadPress',
 u'consider_onset',
 u'Response',
 u'Task',
 u'Trial',
 u'Points',
 u'Error',
 u'catch',
 u'mouse_pos',
 u'Block',
 u'catch_probe',
 u'Probe',
 u'hold_onset',
 u'Move',
 u'decision_onset',
 u'hold_onset_real',
 u'Click']

In [14]:
new_dat[sub_ex]['NlineResults']['run1']['Probe']

[array([57], dtype=uint8),
 array([77], dtype=uint8),
 array([3], dtype=uint8),
 array([21], dtype=uint8),
 array([60], dtype=uint8),
 array([28], dtype=uint8),
 array([85], dtype=uint8),
 array([74], dtype=uint8),
 array([33], dtype=uint8),
 array([7], dtype=uint8),
 array([90], dtype=uint8),
 array([36], dtype=uint8),
 array([11], dtype=uint8),
 array([45], dtype=uint8),
 array([98], dtype=uint8),
 array([65], dtype=uint8),
 array([70], dtype=uint8),
 array([14], dtype=uint8),
 array([80], dtype=uint8),
 array([20], dtype=uint8),
 array([-58], dtype=int16),
 array([-94], dtype=int16),
 array([-86], dtype=int16),
 array([54], dtype=uint8),
 array([-44], dtype=int16),
 array([-78], dtype=int16),
 array([-10], dtype=int16),
 array([48], dtype=uint8),
 array([30], dtype=uint8),
 array([-28], dtype=int16),
 array([96], dtype=uint8),
 array([-34], dtype=int16),
 u'of',
 u'is',
 u'be',
 u'me',
 u'it',
 u'as',
 u'my',
 u'so',
 u'we',
 u'or',
 u'ox',
 u'by',
 u'am',
 u'he',
 u'do',
 u'if']

In [15]:
new_dat[sub_ex]['NlineResults']['run1']['catch_probe']

[array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), 

In [16]:
subj = data_dict.keys()
tasks = [Nline]
tuples = []
rows = len(data_dict[sub_ex]['p'][Nline][0][0][:])-1
for s in subj:
    runs = new_dat[s]['NlineResults'].keys()
    for run in runs:
        for i in range(0,rows):
            tuples.append((s, run, i))
len(tuples)
#iterables = [subj,tasks,runs]
indexes = pd.MultiIndex.from_tuples(tuples, names=['Subj', 'Run', 'Trial'])
nline_cols = len(new_dat[sub_ex][Nline]['run1'].keys())

In [17]:
indexes[90]

('s_02009', 'run3', 42)

In [18]:
indexes[1][1]

'run1'

In [19]:
varnames = new_dat[sub_ex][Nline]['run1'].keys()
varnames[24]

u'Block'

In [20]:
len(indexes)

4224

In [21]:
# Code empty cells of probes and catch_probes as Nan
Dic_list = []
probes = ['catch_probe']
for data in indexes:
    temp_dict = {}
    for var in varnames:
        if var == probes[0]:
            if len(new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]]) == 0:
                new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]] = np.array([np.nan])
            temp_dict[var] = new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]][0]
        else:
            temp_dict[var] = new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]]
    Dic_list.append(temp_dict)

In [158]:
#Create dataframe
nline_df = pd.DataFrame(Dic_list, index=indexes)
sum(nline_df.loc[sub_ex].loc['run1'].iloc[0:48]['catch'])

12

In [159]:
nline_df.loc[sub_ex].loc['run1'].iloc[0:10]['Error']

Trial
0   -0.023744
1   -0.025507
2    0.000000
3    0.000000
4   -0.027313
5    0.001938
6   -0.046035
7    0.000000
8    0.070881
9    0.026916
Name: Error, dtype: float64

In [160]:
nline_df.index.names = ['Subject', 'Run', 'Trial']
nline_df.index.names

FrozenList([u'Subject', u'Run', u'Trial'])

In [161]:
test = nline_df['Probe']
for i in range(0,len(test)):
    test[i] = np.ravel(test[i])
    test[i] = test[i][0]
nline_df['Probe'] = test
nline_df['Probe']

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


Subject  Run   Trial
s_02009  run1  0         57
               1         77
               2          3
               3         21
               4         60
               5         28
               6         85
               7         74
               8         33
               9          7
               10        90
               11        36
               12        11
               13        45
               14        98
               15        65
               16        70
               17        14
               18        80
               19        20
               20       -58
               21       -94
               22       -86
               23        54
               24       -44
               25       -78
               26       -10
               27        48
               28        30
               29       -28
                       ... 
s_02022  run4  18        or
               19        my
               20        of
               21        we

### Create Stim Labels

In [162]:
#now nline
#nline_df['Num'] = nline_df['Num'].map('{:.0f}'.format)
#nline_df['Denom'] = nline_df['Denom'].map('{:.0f}'.format)
#nline_df['Stim'] = nline_df['Num']+'/'+nline_df['Denom']
#nline_df['Stim']

In [163]:
nline_df.columns

Index([u'BadPress', u'Block', u'Click', u'Correct', u'Error', u'ITI_onset',
       u'ITI_onset_real', u'Line_pct', u'Move', u'Points', u'Probe', u'RT',
       u'RTHold', u'Response', u'Slow', u'Task', u'TestX', u'Trial', u'Wrong',
       u'catch', u'catch_probe', u'consider_onset', u'consider_onset_real',
       u'decision_end', u'decision_end_real', u'decision_onset',
       u'decision_onset_real', u'hold', u'hold_onset', u'hold_onset_real',
       u'iti', u'mouse_pos'],
      dtype='object')

In [164]:
#Make task as string
nline_df['Task'] = nline_df['Task'].astype(str)
nline_df['Task'][nline_df['Task']=='1'] = 'Pos'
nline_df['Task'][nline_df['Task']=='2'] = 'Neg'
nline_df['Task'][nline_df['Task']=='3'] = 'Word'
nline_df['Task'].iloc[16]

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


'Neg'

In [165]:
nline_df['Task']

Subject  Run   Trial
s_02009  run1  0         Pos
               1         Pos
               2         Pos
               3         Pos
               4         Pos
               5         Pos
               6         Pos
               7         Pos
               8         Pos
               9         Pos
               10        Pos
               11        Pos
               12        Pos
               13        Pos
               14        Pos
               15        Pos
               16        Neg
               17        Neg
               18        Neg
               19        Neg
               20        Neg
               21        Neg
               22        Neg
               23        Neg
               24        Neg
               25        Neg
               26        Neg
               27        Neg
               28        Neg
               29        Neg
                        ... 
s_02022  run4  18       Word
               19       Word
               20     

In [166]:
nline_df['Dist0'] = abs(nline_df['Line_pct'] - 0)
nline_df['Dist100'] = abs(nline_df['Line_pct'] - 1)
nline_df['Dist50'] = abs(nline_df['Line_pct'] - 0.5)
nline_df['LandmarkDist'] = nline_df[['Dist0','Dist100','Dist50']].min(axis=1) 
nline_df['LandmarkDist']

Subject  Run   Trial
s_02009  run1  0        0.07
               1        0.23
               2        0.03
               3        0.21
               4        0.10
               5        0.22
               6        0.15
               7        0.24
               8        0.17
               9        0.07
               10       0.10
               11       0.14
               12       0.11
               13       0.05
               14       0.02
               15       0.15
               16       0.15
               17       0.07
               18       0.10
               19       0.10
               20       0.21
               21       0.03
               22       0.07
               23       0.23
               24       0.22
               25       0.11
               26       0.05
               27       0.24
               28       0.15
               29       0.14
                        ... 
s_02022  run4  18       0.15
               19       0.03
               20     

# Create Onset Files

In [167]:
nline_df['Missed'] = 0

In [168]:
nline_df['Missed'][(nline_df.catch < 1) & (nline_df.Error == 1)] = 1
nline_df[(nline_df.Missed == 1)]['Error']

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


Subject  Run   Trial
s_02009  run1  22       1
s_02003  run1  0        1
               15       1
               26       1
               36       1
         run3  20       1
               23       1
         run4  1        1
s_02002  run1  9        1
               29       1
s_02001  run1  25       1
s_02007  run4  24       1
s_02006  run1  12       1
         run2  35       1
s_02005  run1  0        1
               7        1
               20       1
               32       1
               34       1
               36       1
               43       1
         run3  13       1
               22       1
               47       1
         run2  15       1
               20       1
               21       1
               29       1
         run4  6        1
               9        1
                       ..
s_02020  run1  43       1
         run3  46       1
         run2  35       1
               46       1
         run4  12       1
               24       1
               43

In [169]:
nline_df['Missed'][(nline_df.catch < 1) & (abs(nline_df.Error) >= 0.1)] = 1
nline_df[(nline_df.Missed == 1)]['Error']

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


Subject  Run   Trial
s_02009  run1  22       1.000000
               24       0.220000
s_02003  run1  0        1.000000
               15       1.000000
               26       1.000000
               36       1.000000
         run3  20       1.000000
               23       1.000000
         run4  1        1.000000
               47      -0.137533
s_02002  run1  9        1.000000
               29       1.000000
         run2  34      -0.687004
               43       0.575374
s_02001  run1  25       1.000000
         run2  23       0.205330
s_02007  run1  18       0.107709
         run2  5       -0.210529
         run4  9       -0.962379
               24       1.000000
s_02006  run1  12       1.000000
               32      -0.142687
         run3  38       0.208590
               39       0.402335
         run2  35       1.000000
s_02005  run1  0        1.000000
               7        1.000000
               20       1.000000
               27      -0.275551
               32     

In [170]:
nline_df['problem_trial_cons'] = 0
nline_df['problem_trial_dec'] = 0

In [171]:
nline_df.loc[nline_df.RT == -1, 'RT'] = 'NaN'

In [172]:
nline_df.columns

Index([           u'BadPress',               u'Block',               u'Click',
                   u'Correct',               u'Error',           u'ITI_onset',
            u'ITI_onset_real',            u'Line_pct',                u'Move',
                    u'Points',               u'Probe',                  u'RT',
                    u'RTHold',            u'Response',                u'Slow',
                      u'Task',               u'TestX',               u'Trial',
                     u'Wrong',               u'catch',         u'catch_probe',
            u'consider_onset', u'consider_onset_real',        u'decision_end',
         u'decision_end_real',      u'decision_onset', u'decision_onset_real',
                      u'hold',          u'hold_onset',     u'hold_onset_real',
                       u'iti',           u'mouse_pos',               u'Dist0',
                   u'Dist100',              u'Dist50',        u'LandmarkDist',
                    u'Missed',  u'problem_trial_cons

In [173]:
nline_df.head()

BadPress  Block  Click  Correct     Error  ITI_onset  \
Subject Run  Trial                                                         
s_02009 run1 0             0      1      1     0.57 -0.023744       14.0   
             1             0      1      1     0.77 -0.025507       24.5   
             2             0      1      0     0.00  0.000000       34.0   
             3             0      1      0     0.00  0.000000       45.5   
             4             0      1      1     0.60 -0.027313       56.0   

                    ITI_onset_real  Line_pct  Move  Points        ...          \
Subject Run  Trial                                                ...           
s_02009 run1 0           14.105561      0.57     0       1        ...           
             1           24.504968      0.77     0       2        ...           
             2           34.002677      0.03     0       3        ...           
             3           45.504889      0.21     0       4        ...           
             4           56.007326      0.60     0       5        ...           

                   hold_onset_real  iti  mouse_pos  Dist0  Dist100 Dist50  \
Subject Run  Trial                                                          
s_02009 run1 0           18.005189  3.5        0.5   0.57     0.43   0.07   
             1           28.501439  3.5        0.5   0.77     0.23   0.27   
             2           38.502979  4.0        0.5   0.03     0.97   0.47   
             3           49.502440  3.5        0.5   0.21     0.79   0.29   
             4           61.503006  5.0        0.5   0.60     0.40   0.10   

                    LandmarkDist  Missed  problem_trial_cons  \
Subject Run  Trial                                             
s_02009 run1 0              0.07       0                   0   
             1              0.23       0                   0   
             2              0.03       0                   0   
             3              0.21       0                   0   
             4              0.10       0                   0   

                    problem_trial_dec  
Subject Run  Trial                     
s_02009 run1 0                      0  
             1                      0  
             2                      0  
             3                      0  
             4                      0  

[5 rows x 39 columns]

In [174]:
nline_df.loc[nline_df['consider_onset_real'] - nline_df['consider_onset'] > 0.5,'problem_trial_cons'] = 1
nline_df.loc[nline_df['consider_onset_real'] - nline_df['consider_onset'] > 0.5,'problem_trial_cons']

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.
  from ipykernel import kernelapp as app


Subject  Run   Trial
s_02005  run2  20       1
s_02012  run4  18       1
               19       1
s_02014  run2  41       1
               42       1
               43       1
s_02017  run3  38       1
s_02024  run2  7        1
Name: problem_trial_cons, dtype: int64

In [176]:
nline_df.loc[nline_df['decision_onset_real'] - nline_df['decision_onset'] > 0.5,'problem_trial_dec'] = 1
nline_df.loc[nline_df['decision_onset_real'] - nline_df['decision_onset'] > 0.5,'problem_trial_dec']

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.
  from ipykernel import kernelapp as app


Subject  Run   Trial
s_02019  run4  43       1
s_02012  run4  17       1
               18       1
               19       1
s_02014  run2  40       1
               41       1
               42       1
s_02015  run2  5        1
s_02017  run3  6        1
               37       1
s_02024  run2  6        1
               7        1
               16       1
         run4  23       1
Name: problem_trial_dec, dtype: int64

In [190]:
import string
offset = 2 #This might be 18 if it includes the 4 deleted volumes
tasks = nline_df.groupby('Task')
labels = tasks.indices.keys()
phase = ['cons', 'dec']
big_dict = {}
## For testing
S = ['s_02015']
R = ['run2']

## Breaks always happen at the same time in the sequence Currently only subtracting 2
# [[188, 6, 1],[386, 6, 1]] with 18s offset
break_onset_d = {'onset':[204,402],
                 'duration':[6,6],
                 'trial_type':['break','break'],
                 'phase':['break','break'],
                 'probe':['NaN','NaN'],
                 'Line_pct':['NaN','NaN'],
                 'Response':['NaN','NaN'],
                 'RT':['NaN','NaN'],
                 'RTHold':['NaN','NaN'],
                 'catch':['NaN','NaN'],
                 'Missed':['NaN','NaN'],
                 'problem_trial':['NaN','NaN']}
break_onset = pd.DataFrame(break_onset_d)

#for s in S:
for s in nline_df.index.levels[0]:
    print s
    big_dict[s] = {}
    #dec_ctch_onset[s] = {}
    #for r in R:
    for r in nline_df.index.levels[1]:
        #print r
        big_dict[s][r] = {}
        ctch = nline_df.loc[s].loc[r]['catch']
        
        problem_con = nline_df.loc[s].loc[r]['consider_onset_real'] - nline_df.loc[s].loc[r]['consider_onset']
        problem_dec = nline_df.loc[s].loc[r]['decision_onset_real'] - nline_df.loc[s].loc[r]['decision_onset']
        prob_con_idx = problem_con > 0.5
        prob_dec_idx = problem_dec > 0.5
        
        if len(nline_df.loc[s].loc[r]['hold']) == 0:
            hold = 2.5
        else:
            hold = min(nline_df.loc[s].loc[r]['hold'])
        cons_duration = hold + cons_time
        
        for ph in phase:
            if ph == 'dec':
                df_dec = nline_df.loc[s].loc[r]
                df_dec['onset'] = df_dec['decision_onset_real'] - offset
                df_dec['duration'] = dec_time
                df_dec['trial_type'] = df_dec.Task
                df_dec['probe'] = df_dec.Probe
                df_dec['phase'] = 'marking'
                df_dec = df_dec.loc[:,['onset','duration','trial_type','phase','probe','Line_pct','Response','RT',
                                       'RTHold','catch','Missed','problem_trial_dec']]
                df_dec.rename(columns={'problem_trial_dec':'problem_trial'},inplace=True)
            elif ph == 'cons':
                df_cons = nline_df.loc[s].loc[r]
                df_cons['onset'] = df_cons['consider_onset_real'] - offset
                df_cons['duration'] = cons_duration
                df_cons['trial_type'] = df_cons.Task
                df_cons['probe'] = df_cons.Probe
                df_cons['phase'] = 'encoding'
                df_cons['catch'] = 0
                df_cons = df_cons.loc[:,['onset','duration','trial_type','phase','probe','Line_pct','Response','RT',
                                         'RTHold','catch','Missed','problem_trial_cons']]
                df_cons.rename(columns={'problem_trial_cons':'problem_trial'},inplace=True)
        tmp_merged = pd.concat([df_cons, df_dec,break_onset],join='outer',)
        tmp_merged = tmp_merged.sort('onset')
        tmp_merged.rename(columns={'Line_pct':'line_pct','Response':'response','Missed':'missed'},inplace=True)
        tmp_merged = tmp_merged[['onset','duration','trial_type','phase','probe','line_pct','response','RT',
                                         'RTHold','catch','missed','problem_trial']]
        big_dict[s][r]['Onsets'] = tmp_merged

s_02001
s_02002
s_02003
s_02004
s_02005
s_02006
s_02007
s_02009
s_02010
s_02011
s_02012
s_02014
s_02015
s_02016
s_02017
s_02018
s_02019
s_02020
s_02021
s_02022
s_02023
s_02024
s_02027


/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:72: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)


In [191]:
df_dec

onset  duration trial_type    phase probe  Line_pct  Response  \
Trial                                                                       
0       20.007407         3       Word  marking    or      0.77  0.777533   
1       30.507747         3       Word  marking    we      0.03  0.017621   
2       42.528763         3       Word  marking    be      0.65  0.645374   
3       55.008078         3       Word  marking    so      0.45  0.440529   
4       68.508412         3       Word  marking    as      0.07  0.000000   
5       79.508728         3       Word  marking    it      0.90  0.000000   
6       95.509317         3       Word  marking    am      0.98  0.995595   
7      108.693115         3       Word  marking    my      0.57  0.592511   
8      119.009793         3       Word  marking    he      0.36  0.000000   
9      130.010254         3       Word  marking    ox      0.74  0.744493   
10     142.510500         3       Word  marking    me      0.33  0.308370   
11     154.013506         3       Word  marking    by      0.28  0.275330   
12     167.511261         3       Word  marking    is      0.21  0.202643   
13     177.511669         3       Word  marking    do      0.11  0.110132   
14     191.512042         3       Word  marking    if      0.85  0.843612   
15     201.012060         3       Word  marking    of      0.60  0.000000   
16     221.529297         3        Pos  marking    74      0.74  0.000000   
17     231.512966         3        Pos  marking    90      0.90  0.856828   
18     244.504542         3        Pos  marking    60      0.60  0.592511   
19     256.519548         3        Pos  marking    45      0.45  0.447137   
20     272.514172         3        Pos  marking     3      0.03  0.037445   
21     284.014369         3        Pos  marking    33      0.33  0.354626   
22     296.002117         3        Pos  marking    57      0.57  0.585903   
23     307.500969         3        Pos  marking    28      0.28  0.000000   
24     317.521504         3        Pos  marking    65      0.65  0.632159   
25     327.502928         3        Pos  marking    77      0.77  0.737885   
26     341.015800         3        Pos  marking    98      0.98  1.000000   
27     354.533004         3        Pos  marking     7      0.07  0.129956   
28     367.022864         3        Pos  marking    85      0.85  0.000000   
29     379.023121         3        Pos  marking    21      0.21  0.229075   
30     389.010691         3        Pos  marking    11      0.11  0.000000   
31     399.005076         3        Pos  marking    36      0.36  0.000000   
32     418.011614         3        Neg  marking   -58      0.21  0.295154   
33     429.004190         3        Neg  marking   -44      0.28  0.000000   
34     442.501981         3        Neg  marking   -34      0.33  0.000000   
35     456.002413         3        Neg  marking   -10      0.45  0.433921   
36     466.502742         3        Neg  marking    48      0.74  0.000000   
37     478.511170         3        Neg  marking   -78      0.11  0.103524   
38     488.525759         3        Neg  marking    14      0.57  0.000000   
39     499.509755         3        Neg  marking    96      0.98  0.995595   
40     511.526475         3        Neg  marking    20      0.60  0.599119   
41     522.028899         3        Neg  marking    54      0.77  0.744493   
42     533.504324         3        Neg  marking    70      0.85  0.837004   
43     546.504682         3        Neg  marking    30      0.65  0.651982   
44     558.529838         3        Neg  marking   -94      0.03  0.070485   
45     571.013718         3        Neg  marking   -86      0.07  0.182819   
46     581.515772         3        Neg  marking   -28      0.36  0.000000   
47     597.006269         3        Neg  marking    80      0.90  0.909692   

            RT    RTHold  catch  Missed  problem_trial  
Trial                                                   
0      2.59571  0.456348      0       0        

In [189]:
tmp_merged.head(40)

onset  duration trial_type     phase probe line_pct   response  \
Trial                                                                        
0       15.501565         3        Pos  encoding    28     0.28   0.162996   
0       21.504922         3        Pos   marking    28     0.28   0.162996   
1       29.502176         3        Pos  encoding    74     0.74   0.744493   
1       33.005452         3        Pos   marking    74     0.74   0.744493   
2       39.002864         3        Pos  encoding    98     0.98          1   
2       42.005852         3        Pos   marking    98     0.98          1   
3       49.001308         3        Pos  encoding    60      0.6   0.592511   
3       52.539472         3        Pos   marking    60      0.6   0.592511   
4       59.500899         3        Pos  encoding    11     0.11  0.0704846   
4       64.006391         3        Pos   marking    11     0.11  0.0704846   
5       72.502433         3        Pos  encoding    90      0.9          0   
5       81.573348         3        Pos   marking    90      0.9          0   
6       86.002770         3        Pos  encoding    85     0.85   0.856828   
6       90.007038         3        Pos   marking    85     0.85   0.856828   
7       97.501817         3        Pos  encoding    57     0.57   0.559471   
7      103.007546         3        Pos   marking    57     0.57   0.559471   
8      110.502539         3        Pos  encoding     7     0.07          0   
8      114.007803         3        Pos   marking     7     0.07          0   
9      123.501770         3        Pos  encoding     3     0.03          0   
9      127.508158         3        Pos   marking     3     0.03          0   
10     133.501680         3        Pos  encoding    21     0.21    0.11674   
10     140.008429         3        Pos   marking    21     0.21    0.11674   
11     146.502203         3        Pos  encoding    45     0.45   0.407489   
11     151.008828         3        Pos   marking    45     0.45   0.407489   
12     161.001909         3        Pos  encoding    65     0.65          0   
12     165.008899         3        Pos   marking    65     0.65          0   
13     172.502658         3        Pos  encoding    77     0.77   0.797357   
13     175.509375         3        Pos   marking    77     0.77   0.797357   
14     184.501812         3        Pos  encoding    36     0.36          0   
14     189.009898         3        Pos   marking    36     0.36          0   
15     196.002719         3        Pos  encoding    33     0.33          0   
15     201.010264         3        Pos   marking    33     0.33          0   
0      204.000000         6      break     break   NaN      NaN        NaN   
16     215.002424         3        Neg  encoding    80      0.9   0.876652   
16     218.510672         3        Neg   marking    80      0.9   0.876652   
17     226.002312         3        Neg  encoding   -34     0.33          0   
17     231.010947         3        Neg   marking   -34     0.33          0   
18     240.001746         3        Neg  encoding   -10     0.45   0.460352   
18     244.011440         3        Neg   marking   -10     0.45   0.460352   
19     251.002110         3        Neg  encoding   -44     0.28    0.30837   

            RT    RTHold catch missed problem_trial  
Trial                                                
0      2.31156  0.499162     0      1             0  
0      2.31156  0.499162     0      1             0  
1      2.21259  0.391442     0      0             0  
1      2.21259  0.391442     0      0             0  
2      1.40923  0.503994     0      0             0  
2      1.40923  0.503994     0      0             0  
3      1.92549  0.424231     0      0             0  
3      1.92549  0.424231     0      0             0  
4      1.97527  0.346338     0      0             0  
4      1.97527  0.346338     0      0             0  
5          NaN  0.405495     0      1             0  
5          NaN  0.405495     0   

In [196]:
big_dict['s_02015']['run2']['Onsets'].head(40)

onset  duration trial_type     phase probe line_pct   response  \
Trial                                                                        
0       15.501565         3        Pos  encoding    28     0.28   0.162996   
0       21.504922         3        Pos   marking    28     0.28   0.162996   
1       29.502176         3        Pos  encoding    74     0.74   0.744493   
1       33.005452         3        Pos   marking    74     0.74   0.744493   
2       39.002864         3        Pos  encoding    98     0.98          1   
2       42.005852         3        Pos   marking    98     0.98          1   
3       49.001308         3        Pos  encoding    60      0.6   0.592511   
3       52.539472         3        Pos   marking    60      0.6   0.592511   
4       59.500899         3        Pos  encoding    11     0.11  0.0704846   
4       64.006391         3        Pos   marking    11     0.11  0.0704846   
5       72.502433         3        Pos  encoding    90      0.9          0   
5       81.573348         3        Pos   marking    90      0.9          0   
6       86.002770         3        Pos  encoding    85     0.85   0.856828   
6       90.007038         3        Pos   marking    85     0.85   0.856828   
7       97.501817         3        Pos  encoding    57     0.57   0.559471   
7      103.007546         3        Pos   marking    57     0.57   0.559471   
8      110.502539         3        Pos  encoding     7     0.07          0   
8      114.007803         3        Pos   marking     7     0.07          0   
9      123.501770         3        Pos  encoding     3     0.03          0   
9      127.508158         3        Pos   marking     3     0.03          0   
10     133.501680         3        Pos  encoding    21     0.21    0.11674   
10     140.008429         3        Pos   marking    21     0.21    0.11674   
11     146.502203         3        Pos  encoding    45     0.45   0.407489   
11     151.008828         3        Pos   marking    45     0.45   0.407489   
12     161.001909         3        Pos  encoding    65     0.65          0   
12     165.008899         3        Pos   marking    65     0.65          0   
13     172.502658         3        Pos  encoding    77     0.77   0.797357   
13     175.509375         3        Pos   marking    77     0.77   0.797357   
14     184.501812         3        Pos  encoding    36     0.36          0   
14     189.009898         3        Pos   marking    36     0.36          0   
15     196.002719         3        Pos  encoding    33     0.33          0   
15     201.010264         3        Pos   marking    33     0.33          0   
0      204.000000         6      break     break   NaN      NaN        NaN   
16     215.002424         3        Neg  encoding    80      0.9   0.876652   
16     218.510672         3        Neg   marking    80      0.9   0.876652   
17     226.002312         3        Neg  encoding   -34     0.33          0   
17     231.010947         3        Neg   marking   -34     0.33          0   
18     240.001746         3        Neg  encoding   -10     0.45   0.460352   
18     244.011440         3        Neg   marking   -10     0.45   0.460352   
19     251.002110         3        Neg  encoding   -44     0.28    0.30837   

            RT    RTHold catch missed problem_trial  
Trial                                                
0      2.31156  0.499162     0      1             0  
0      2.31156  0.499162     0      1             0  
1      2.21259  0.391442     0      0             0  
1      2.21259  0.391442     0      0             0  
2      1.40923  0.503994     0      0             0  
2      1.40923  0.503994     0      0             0  
3      1.92549  0.424231     0      0             0  
3      1.92549  0.424231     0      0             0  
4      1.97527  0.346338     0      0             0  
4      1.97527  0.346338     0      0             0  
5          NaN  0.405495     0      1             0  
5          NaN  0.405495     0   

## Save Files

In [203]:
for s in big_dict.keys():
    print s
    #Laptop
    #path = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LandmarksFull'
    #path = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LandmarksFull/'+s+'/'
    #Desktop
    #path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LSS'
    #path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LSS/'+s+'/'
    #path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/Events_BIDS/'
    path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/Events_BIDS/'+'sub-'+s[2:]+'/'
    os.makedirs(path)
    for r in big_dict[s].keys():
        print r
        ses_path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/Events_BIDS/'+'sub-'+s[2:]+'/'+'ses-0'+r[3]+'/func/'
        os.makedirs(ses_path)
        event_filename = 'sub-'+s[2:]+'_ses-0'+r[3]+'_task-numbers_run-'+r[3]+'_events.tsv'
        event_pathfile = ses_path+event_filename
        big_dict[s][r]['Onsets'].to_csv(event_pathfile, sep='\t', header=True, index=False)

s_02009
run1
run3
run2
run4
s_02003
run1
run3
run2
run4
s_02002
run1
run3
run2
run4
s_02001
run1
run3
run2
run4
s_02007
run1
run3
run2
run4
s_02006
run1
run3
run2
run4
s_02005
run1
run3
run2
run4
s_02004
run1
run3
run2
run4
s_02018
run1
run3
run2
run4
s_02019
run1
run3
run2
run4
s_02010
run1
run3
run2
run4
s_02011
run1
run3
run2
run4
s_02012
run1
run3
run2
run4
s_02014
run1
run3
run2
run4
s_02015
run1
run3
run2
run4
s_02016
run1
run3
run2
run4
s_02017
run1
run3
run2
run4
s_02024
run1
run3
run2
run4
s_02027
run1
run3
run2
run4
s_02021
run1
run3
run2
run4
s_02020
run1
run3
run2
run4
s_02023
run1
run3
run2
run4
s_02022
run1
run3
run2
run4
