In [1]:
#Opened with --pylab flag
#Need to create code to analyze piot data
import pandas as pd
import numpy as np
from scipy import io
import os
import glob

In [2]:
## Laptop
#filepath = '/Users/frankkanayet/Dropbox/NLineExperiment/PilotData'
#filepath = '/Users/frankkanayet/Dropbox/NLineExperiment/PilotData/test3s'
#filepath = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data'

## Desktop
#filepath = '/Users/frankanayet/Dropbox/NLineExperiment/Data'
filepath = '/Users/frankanayet/Google Drive/NLineData/Beh_Data'
os.chdir(filepath)

In [3]:
print 'Pandas version ' + pd.__version__

Pandas version 0.17.1


In [4]:
filenames = glob.glob('Nline_*.mat')
print filenames
#index to isolate subj numbers
data_dict = {}
for i in filenames:
    id1 = filenames[0].find('_') + 1
    id2 = filenames[0].find('-')
    sub_nbr = i[id1:id2]
    sub_name = i
    s_id = 's_'+sub_nbr
    data_dict[s_id] = io.loadmat(sub_name)

#sub_name = filenames[0] #This will be changed to a loop for all subjects later
#mat = io.loadmat(sub_name)
data_dict.keys()

['Nline_02001-Mar1615.mat', 'Nline_02002-Mar1915.mat', 'Nline_02003-Mar2015a.mat', 'Nline_02004-Mar2315a.mat', 'Nline_02005-Mar2315a.mat', 'Nline_02006-Mar2315a.mat', 'Nline_02007-Mar2415a.mat', 'Nline_02009-Mar2615a.mat', 'Nline_02010-Mar2615a.mat', 'Nline_02011-Mar2615a.mat', 'Nline_02012-Apr0215a.mat', 'Nline_02014-Apr0315a.mat', 'Nline_02015Apr2715a.mat', 'Nline_02016-Apr2715a.mat', 'Nline_02017-Apr2815a.mat', 'Nline_02018-Apr2815a.mat', 'Nline_02019-Apr2915a.mat', 'Nline_02020-May1815a.mat', 'Nline_02021-May2515a.mat', 'Nline_02022-May2515a.mat', 'Nline_02023-May2715a.mat', 'Nline_02024-May2815a.mat', 'Nline_02027-Jun0115a.mat']


['s_02009',
 's_02003',
 's_02002',
 's_02001',
 's_02007',
 's_02006',
 's_02005',
 's_02004',
 's_02018',
 's_02019',
 's_02010',
 's_02011',
 's_02012',
 's_02014',
 's_02015',
 's_02016',
 's_02017',
 's_02024',
 's_02027',
 's_02021',
 's_02020',
 's_02023',
 's_02022']

In [5]:
sub_ex = data_dict.keys()[0]

In [6]:
#data_dict['s_00011']['p']

In [7]:
#for i in data_dict:
#    data_dict[i].pop('__header__')
#    data_dict[i].pop('__version__')
#    data_dict[i].pop('__globals__')
#data_dict['s_00011'].keys()

In [8]:
## The indexes of zeros are as follows [0][0][x][y][z][0] The x y z are the 3 dimensions of the data 3d matrix the zeros are padding
data_dict[sub_ex]['p']['NlineResults'][0][0][0][5][0][0]
len(data_dict[sub_ex]['p']['NlineResults'][0][0][:])

49

In [9]:
data_dict[sub_ex]['p'].dtype.names

('ramp_up',
 'Mean_ITI',
 'Mean_hold',
 'decision',
 'consider',
 'runs',
 'nStim',
 'ntasks',
 'tasks',
 'trialSecs',
 'lineLength',
 'speed',
 'run_order',
 'NlineResults',
 'time_Runs',
 'task_transition',
 'start_Nline',
 'finish_Nline')

In [10]:
cons_time = data_dict[sub_ex]['p']['consider'][0][0][0][0]
dec_time = data_dict[sub_ex]['p']['decision'][0][0][0][0]

In [11]:
new_dat = {}
#new_df = {}
for s in data_dict:
    tasks = ['NlineResults']
    new_dat[s]={}
    #new_df[s] = {}
    for task in tasks:
        dat = data_dict[s]['p'][task]
        num_fields = len(data_dict[s]['p'][task][0][0][0])
        dat_names = []
        for k in range(0,num_fields):
            dat_names.append(dat[0][0][0][k][0][0])
        new_dat[s][task] = {}
        runs = data_dict[s]['p']['runs'][0][0][0][0]
        for run in range(0,runs):
            run_name = 'run'+str(run+1)
            new_dat[s][task][run_name] = {}
            for i in range(0,len(dat_names)):
                new_dat[s][task][run_name][dat_names[i]] = []
                for j in range(0,len(dat[0][0][:])-1):
                    if dat_names[i] == 'catch_probe':
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run])
                    elif dat_names[i] == 'Probe':
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run][0])
                    else:
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run][0][0])
#legible access to the data
Nline = 'NlineResults' #numberline

In [12]:
new_dat[sub_ex]['NlineResults']['run1'].keys()

[u'Slow',
 u'Line_pct',
 u'iti',
 u'TestX',
 u'ITI_onset_real',
 u'consider_onset_real',
 u'ITI_onset',
 u'RT',
 u'hold',
 u'decision_end',
 u'decision_onset_real',
 u'RTHold',
 u'decision_end_real',
 u'Correct',
 u'Wrong',
 u'BadPress',
 u'consider_onset',
 u'Response',
 u'Task',
 u'Trial',
 u'Points',
 u'Error',
 u'catch',
 u'mouse_pos',
 u'Block',
 u'catch_probe',
 u'Probe',
 u'hold_onset',
 u'Move',
 u'decision_onset',
 u'hold_onset_real',
 u'Click']

In [13]:
new_dat[sub_ex]['NlineResults']['run1']['Probe']

[array([57], dtype=uint8),
 array([77], dtype=uint8),
 array([3], dtype=uint8),
 array([21], dtype=uint8),
 array([60], dtype=uint8),
 array([28], dtype=uint8),
 array([85], dtype=uint8),
 array([74], dtype=uint8),
 array([33], dtype=uint8),
 array([7], dtype=uint8),
 array([90], dtype=uint8),
 array([36], dtype=uint8),
 array([11], dtype=uint8),
 array([45], dtype=uint8),
 array([98], dtype=uint8),
 array([65], dtype=uint8),
 array([70], dtype=uint8),
 array([14], dtype=uint8),
 array([80], dtype=uint8),
 array([20], dtype=uint8),
 array([-58], dtype=int16),
 array([-94], dtype=int16),
 array([-86], dtype=int16),
 array([54], dtype=uint8),
 array([-44], dtype=int16),
 array([-78], dtype=int16),
 array([-10], dtype=int16),
 array([48], dtype=uint8),
 array([30], dtype=uint8),
 array([-28], dtype=int16),
 array([96], dtype=uint8),
 array([-34], dtype=int16),
 u'of',
 u'is',
 u'be',
 u'me',
 u'it',
 u'as',
 u'my',
 u'so',
 u'we',
 u'or',
 u'ox',
 u'by',
 u'am',
 u'he',
 u'do',
 u'if']

In [14]:
new_dat[sub_ex]['NlineResults']['run1']['catch_probe']

[array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), 

In [15]:
subj = data_dict.keys()
tasks = [Nline]
tuples = []
rows = len(data_dict[sub_ex]['p'][Nline][0][0][:])-1
for s in subj:
    runs = new_dat[s]['NlineResults'].keys()
    for run in runs:
        for i in range(0,rows):
            tuples.append((s, run, i))
len(tuples)
#iterables = [subj,tasks,runs]
indexes = pd.MultiIndex.from_tuples(tuples, names=['Subj', 'Run', 'Trial'])
nline_cols = len(new_dat[sub_ex][Nline]['run1'].keys())

In [16]:
indexes[90]

('s_02009', 'run3', 42)

In [17]:
indexes[1][1]

'run1'

In [18]:
varnames = new_dat[sub_ex][Nline]['run1'].keys()
varnames[24]

u'Block'

In [19]:
len(indexes)

4224

In [20]:
# Code empty cells of probes and catch_probes as Nan
Dic_list = []
probes = ['catch_probe']
for data in indexes:
    temp_dict = {}
    for var in varnames:
        if var == probes[0]:
            if len(new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]]) == 0:
                new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]] = np.array([np.nan])
            temp_dict[var] = new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]][0]
        else:
            temp_dict[var] = new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]]
    Dic_list.append(temp_dict)

In [21]:
#Create dataframe
nline_df = pd.DataFrame(Dic_list, index=indexes)
sum(nline_df.loc[sub_ex].loc['run1'].iloc[0:48]['catch'])

12

In [22]:
nline_df.loc[sub_ex].loc['run1'].iloc[0:10]['Error']

Trial
0   -0.023744
1   -0.025507
2    0.000000
3    0.000000
4   -0.027313
5    0.001938
6   -0.046035
7    0.000000
8    0.070881
9    0.026916
Name: Error, dtype: float64

In [23]:
nline_df.index.names = ['Subject', 'Run', 'Trial']
nline_df.index.names

FrozenList([u'Subject', u'Run', u'Trial'])

In [24]:
test = nline_df['Probe']
for i in range(0,len(test)):
    test[i] = np.ravel(test[i])
    test[i] = test[i][0]
nline_df['Probe'] = test
nline_df['Probe']

/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


Subject  Run   Trial
s_02009  run1  0         57
               1         77
               2          3
               3         21
               4         60
               5         28
               6         85
               7         74
               8         33
               9          7
               10        90
               11        36
               12        11
               13        45
               14        98
               15        65
               16        70
               17        14
               18        80
               19        20
               20       -58
               21       -94
               22       -86
               23        54
               24       -44
               25       -78
               26       -10
               27        48
               28        30
               29       -28
                       ... 
s_02022  run4  18        or
               19        my
               20        of
               21        we

### Create Stim Labels

In [25]:
#now nline
#nline_df['Num'] = nline_df['Num'].map('{:.0f}'.format)
#nline_df['Denom'] = nline_df['Denom'].map('{:.0f}'.format)
#nline_df['Stim'] = nline_df['Num']+'/'+nline_df['Denom']
#nline_df['Stim']

In [26]:
nline_df.columns

Index([u'BadPress', u'Block', u'Click', u'Correct', u'Error', u'ITI_onset',
       u'ITI_onset_real', u'Line_pct', u'Move', u'Points', u'Probe', u'RT',
       u'RTHold', u'Response', u'Slow', u'Task', u'TestX', u'Trial', u'Wrong',
       u'catch', u'catch_probe', u'consider_onset', u'consider_onset_real',
       u'decision_end', u'decision_end_real', u'decision_onset',
       u'decision_onset_real', u'hold', u'hold_onset', u'hold_onset_real',
       u'iti', u'mouse_pos'],
      dtype='object')

In [27]:
#Make task as string
nline_df['Task'] = nline_df['Task'].astype(str)
nline_df['Task'][nline_df['Task']=='1'] = 'Pos'
nline_df['Task'][nline_df['Task']=='2'] = 'Neg'
nline_df['Task'][nline_df['Task']=='3'] = 'Word'
nline_df['Task'].iloc[16]

/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


'Neg'

In [28]:
nline_df['Task']

Subject  Run   Trial
s_02009  run1  0         Pos
               1         Pos
               2         Pos
               3         Pos
               4         Pos
               5         Pos
               6         Pos
               7         Pos
               8         Pos
               9         Pos
               10        Pos
               11        Pos
               12        Pos
               13        Pos
               14        Pos
               15        Pos
               16        Neg
               17        Neg
               18        Neg
               19        Neg
               20        Neg
               21        Neg
               22        Neg
               23        Neg
               24        Neg
               25        Neg
               26        Neg
               27        Neg
               28        Neg
               29        Neg
                        ... 
s_02022  run4  18       Word
               19       Word
               20     

In [29]:
nline_df['Dist0'] = abs(nline_df['Line_pct'] - 0)
nline_df['Dist100'] = abs(nline_df['Line_pct'] - 1)
nline_df['Dist50'] = abs(nline_df['Line_pct'] - 0.5)
nline_df['LandmarkDist'] = nline_df[['Dist0','Dist100','Dist50']].min(axis=1) 
nline_df['LandmarkDist']

Subject  Run   Trial
s_02009  run1  0        0.07
               1        0.23
               2        0.03
               3        0.21
               4        0.10
               5        0.22
               6        0.15
               7        0.24
               8        0.17
               9        0.07
               10       0.10
               11       0.14
               12       0.11
               13       0.05
               14       0.02
               15       0.15
               16       0.15
               17       0.07
               18       0.10
               19       0.10
               20       0.21
               21       0.03
               22       0.07
               23       0.23
               24       0.22
               25       0.11
               26       0.05
               27       0.24
               28       0.15
               29       0.14
                        ... 
s_02022  run4  18       0.15
               19       0.03
               20     

# Create Onset Files

In [30]:
nline_df['Missed'] = 0

In [31]:
nline_df['Missed'][(nline_df.catch < 1) & (nline_df.Error == 1)] = 1
nline_df[(nline_df.Missed == 1)]['Error']

/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


Subject  Run   Trial
s_02009  run1  22       1
s_02003  run1  0        1
               15       1
               26       1
               36       1
         run3  20       1
               23       1
         run4  1        1
s_02002  run1  9        1
               29       1
s_02001  run1  25       1
s_02007  run4  24       1
s_02006  run1  12       1
         run2  35       1
s_02005  run1  0        1
               7        1
               20       1
               32       1
               34       1
               36       1
               43       1
         run3  13       1
               22       1
               47       1
         run2  15       1
               20       1
               21       1
               29       1
         run4  6        1
               9        1
                       ..
s_02020  run1  43       1
         run3  46       1
         run2  35       1
               46       1
         run4  12       1
               24       1
               43

In [32]:
nline_df['Missed'][(nline_df.catch < 1) & (abs(nline_df.Error) >= 0.1)] = 1
nline_df[(nline_df.Missed == 1)]['Error']

/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


Subject  Run   Trial
s_02009  run1  22       1.000000
               24       0.220000
s_02003  run1  0        1.000000
               15       1.000000
               26       1.000000
               36       1.000000
         run3  20       1.000000
               23       1.000000
         run4  1        1.000000
               47      -0.137533
s_02002  run1  9        1.000000
               29       1.000000
         run2  34      -0.687004
               43       0.575374
s_02001  run1  25       1.000000
         run2  23       0.205330
s_02007  run1  18       0.107709
         run2  5       -0.210529
         run4  9       -0.962379
               24       1.000000
s_02006  run1  12       1.000000
               32      -0.142687
         run3  38       0.208590
               39       0.402335
         run2  35       1.000000
s_02005  run1  0        1.000000
               7        1.000000
               20       1.000000
               27      -0.275551
               32     

In [33]:
import string
vals = ['q1','q2','q3','q4']
val_dict = {'q1':[0,0.25],'q2':[0.25,0.5],'q3':[0.5,0.75],'q4':[0.75,1]}
tasks = nline_df.groupby('Task')
labels = tasks.indices.keys()
phase = ['cons', 'dec']
dec_ctch_onset = {}
big_dict = {}# Breaks always happen at the same time in the sequence
break_onset = [[190, 6, 1],[388, 6, 1]]
for s in nline_df.index.levels[0]:
    print s
    big_dict[s] = {}
    dec_ctch_onset[s] = {}
    for r in nline_df.index.levels[1]:
        #print r
        big_dict[s][r] = {}
        ctch = nline_df.loc[s].loc[r]['catch']
        if len(nline_df.loc[s].loc[r]['hold']) == 0:
            hold = 2.5
        else:
            hold = min(nline_df.loc[s].loc[r]['hold'])
        dec_ctch_tmp = nline_df.loc[s].loc[r]['decision_onset_real'] - 16
        dec_ctch_tmp = dec_ctch_tmp[ctch==1]
        big_dict[s][r]['dec_ctch_onset'] = pd.DataFrame.from_items([('time',dec_ctch_tmp[dec_ctch_tmp>=0]),('duration',dec_time),('val',1)])
        cons_duration = hold + cons_time
        for lab in labels:
            #print lab
            big_dict[s][r][lab] = {}
            Task = nline_df.loc[s].loc[r]['Task']
            line_pct = nline_df.loc[s].loc[r]['Line_pct']
            for ph in phase:
                if ph == 'dec':
                    big_dict[s][r][lab][ph] = {}
                    for val in vals:
                        big_dict[s][r][lab][ph][str(val)] = {}
                        tmp_int = nline_df.loc[s].loc[r]['decision_onset_real'] - 16
                        tmp_int = tmp_int[ctch==0]
                        tmp_int = tmp_int[Task==lab]
                        tmp_int = tmp_int[(line_pct>=val_dict[val][0]) & (line_pct<=val_dict[val][1])] 
                        big_dict[s][r][lab][ph][str(val)] = pd.DataFrame.from_items([('time',tmp_int[tmp_int>=0]),('duration',dec_time),('val',1)])
                elif ph == 'cons':
                    big_dict[s][r][lab][ph] = {}
                    for val in vals:
                        big_dict[s][r][lab][ph][str(val)] = {}
                        tmp_int = nline_df.loc[s].loc[r]['consider_onset_real'] - 16
                        tmp_int = tmp_int[Task==lab]
                        tmp_int = tmp_int[(line_pct>=val_dict[val][0]) & (line_pct<=val_dict[val][1])] 
                        big_dict[s][r][lab][ph][str(val)] = pd.DataFrame.from_items([('time',tmp_int[tmp_int>=0]),('duration',cons_duration),('val',1)])
                    

s_02001
s_02002
s_02003
s_02004
s_02005
s_02006
s_02007
s_02009
s_02010
s_02011
s_02012
s_02014
s_02015
s_02016
s_02017
s_02018
s_02019
s_02020
s_02021
s_02022
s_02023
s_02024
s_02027


In [34]:
big_dict['s_02009']['run1']['Neg']['cons']

{'q1':              time  duration  val
 Trial                           
 20     247.003155         3    1
 21     258.003244         3    1
 22     268.003749         3    1
 25     306.002272         3    1, 'q2':              time  duration  val
 Trial                           
 24     293.501679         3    1
 26     320.002866         3    1
 29     357.003193         3    1
 31     382.002508         3    1, 'q3':              time  duration  val
 Trial                           
 17     213.002962         3    1
 19     237.002220         3    1
 27     331.003328         3    1
 28     344.503100         3    1, 'q4':              time  duration  val
 Trial                           
 16     200.502855         3    1
 18     225.001634         3    1
 23     281.501095         3    1
 30     368.502022         3    1}

In [35]:
big_dict['s_02009']['run1']['Neg']['dec']

{'q1':              time  duration  val
 Trial                           
 21     261.507806         3    1
 22     272.008154         3    1
 25     312.009198         3    1, 'q2':              time  duration  val
 Trial                           
 24     299.008807         3    1
 29     361.510471         3    1
 31     385.011124         3    1, 'q3':              time  duration  val
 Trial                           
 17     216.006646         3    1
 19     241.007333         3    1
 27     338.009907         3    1
 28     348.510182         3    1, 'q4':              time  duration  val
 Trial                           
 16     207.006346         3    1
 30     372.010803         3    1}

In [36]:
big_dict['s_02009']['run1']['dec_ctch_onset']

time  duration  val
Trial                           
2       26.501665         3    1
3       37.001938         3    1
7       88.003307         3    1
13     162.005155         3    1
18     230.007030         3    1
20     251.507610         3    1
23     286.008392         3    1
26     323.509529         3    1
35     439.012473         3    1
36     452.500441         3    1
37     467.013342         3    1
47     583.016409         3    1

In [43]:
#miss_dec_onset['s_02003']['run4']

## Save Files

## All runs separate

In [44]:
for s in big_dict.keys():
    print s
    #Laptop
    #path = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LandmarksFull'
    #path = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LandmarksFull/'+s+'/'
    #Desktop
    path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_Size4'
    path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_Size4/'+s+'/'
    os.makedirs(path)
    for r in big_dict[s].keys():
        print r
        dec_ctch_filename = s+'_'+r+'_DEC_CTCH'+'.txt'
        dec_ctch_pathfile = path+dec_ctch_filename
        big_dict[s][r]['dec_ctch_onset'].to_csv(dec_ctch_pathfile, sep='\t', header=False, index=False)
        del big_dict[s][r]['dec_ctch_onset']
        for lab in big_dict[s][r].keys():
            print lab
            for ph in big_dict[s][r][lab].keys():
                print ph
                for val in big_dict[s][r][lab][ph].keys():
                    print val
                    filename = s+'_'+lab+'_'+r+'_'+ph+'_'+val+'.txt'
                    pathfile = path+filename
                    big_dict[s][r][lab][ph][val].to_csv(pathfile, sep='\t', header=False, index=False)

s_02009
run1
Neg
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
Word
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
Pos
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
run3
Neg
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
Word
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
Pos
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
run2
Neg
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
Word
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
Pos
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
run4
Neg
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
Word
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
Pos
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
s_02003
run1
Neg
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
Word
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
Pos
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
run3
Neg
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
Word
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
Pos
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
run2
Neg
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
Word
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
Pos
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
run4
Neg
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
Word
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
Pos
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
s_02002
run1
Neg
cons
q1
q3
q2
q4
dec
q1
q3
q2
q

In [45]:
#Save Break onset file
path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_Size4/'
#Desktop
break_onset = pd.DataFrame.from_items([('time',[190, 388]),('duration',[6,6]),('val',[1,1])])
break_filename = 'Break_onsets.txt'
break_pathfile = path+break_filename
break_onset.to_csv(break_pathfile, sep='\t', header=False, index=False)

## Merge all runs together

In [82]:
nline_df['consider_onset_real_merged'] = nline_df['consider_onset_real'] - 16

In [83]:
nline_df['decision_onset_real_merged'] = nline_df['decision_onset_real'] - 16

In [86]:
nline_df.sort_index(inplace=True)
idx = pd.IndexSlice
nline_df.loc[idx[:,'run2',:],['consider_onset_real_merged','decision_onset_real_merged']] = nline_df.loc[idx[:,'run2',:],['consider_onset_real_merged','decision_onset_real_merged']] +586

In [88]:
nline_df.loc[idx[:,'run3',:],['consider_onset_real_merged','decision_onset_real_merged']] = nline_df.loc[idx[:,'run3',:],['consider_onset_real_merged','decision_onset_real_merged']] +1172

In [89]:
nline_df.loc[idx[:,'run4',:],['consider_onset_real_merged','decision_onset_real_merged']] = nline_df.loc[idx[:,'run4',:],['consider_onset_real_merged','decision_onset_real_merged']] +1758

In [105]:
vals = ['q1','q2','q3','q4']
val_dict = {'q1':[0,0.25],'q2':[0.25,0.5],'q3':[0.5,0.75],'q4':[0.75,1]}
tasks = nline_df.groupby('Task')
labels = tasks.indices.keys()
phase = ['cons', 'dec']
dec_ctch_onset = {}
big_dict = {}# Breaks always happen at the same time in the sequence
break_onset = [[190, 6, 1],[388, 6, 1]]
for s in nline_df.index.levels[0]:
    print s
    big_dict[s] = {}
    dec_ctch_onset[s] = {}
    ctch = nline_df.loc[s]['catch']
    if len(nline_df.loc[s]['hold']) == 0:
        hold = 2.5
    else:
        hold = min(nline_df.loc[s]['hold'])
    cons_duration = hold + cons_time
    for lab in labels:
        #print lab
        big_dict[s][lab] = {}
        dec_ctch_onset[s][lab] = {}
        big_dict[s][lab]['dec_ctch_onset'] = {}
        Task = nline_df.loc[s]['Task']
        line_pct = nline_df.loc[s]['Line_pct']
        dec_ctch_tmp = nline_df.loc[s]['decision_onset_real_merged']
        dec_ctch_tmp = dec_ctch_tmp[ctch==1]
        dec_ctch_tmp = dec_ctch_tmp[Task==lab]
        big_dict[s][lab]['dec_ctch_onset']['catch'] = {}
        big_dict[s][lab]['dec_ctch_onset']['catch'] = pd.DataFrame.from_items([('time',dec_ctch_tmp[dec_ctch_tmp>=0]),('duration',dec_time),('val',1)])
        for ph in phase:
            if ph == 'dec':
                big_dict[s][lab][ph] = {}
                for val in vals:
                    big_dict[s][lab][ph][str(val)] = {}
                    tmp_int = nline_df.loc[s]['decision_onset_real_merged']
                    tmp_int = tmp_int[ctch==0]
                    tmp_int = tmp_int[Task==lab]
                    tmp_int = tmp_int[(line_pct>=val_dict[val][0]) & (line_pct<=val_dict[val][1])] 
                    big_dict[s][lab][ph][str(val)] = pd.DataFrame.from_items([('time',tmp_int[tmp_int>=0]),('duration',dec_time),('val',1)])
            elif ph == 'cons':
                big_dict[s][lab][ph] = {}
                for val in vals:
                    big_dict[s][lab][ph][str(val)] = {}
                    tmp_int = nline_df.loc[s]['consider_onset_real_merged']
                    tmp_int = tmp_int[Task==lab]
                    tmp_int = tmp_int[(line_pct>=val_dict[val][0]) & (line_pct<=val_dict[val][1])] 
                    big_dict[s][lab][ph][str(val)] = pd.DataFrame.from_items([('time',tmp_int[tmp_int>=0]),('duration',cons_duration),('val',1)])
                    
    

s_02001
s_02002
s_02003
s_02004
s_02005
s_02006
s_02007
s_02009
s_02010
s_02011
s_02012
s_02014
s_02015
s_02016
s_02017
s_02018
s_02019
s_02020
s_02021
s_02022
s_02023
s_02024
s_02027


In [108]:
big_dict[s]['Pos']['dec_ctch_onset']

{'catch':                    time  duration  val
 Run  Trial                            
 run1 33      414.503398         3    1
      36      451.508532         3    1
      37      463.008824         3    1
      40      501.011594         3    1
 run2 0       594.010454         3    1
      1       605.510699         3    1
      4       641.514218         3    1
      12      736.514145         3    1
 run3 35     1613.511476         3    1
      37     1636.512135         3    1
      38     1649.514792         3    1
      41     1686.523568         3    1
 run4 16     1965.529297         3    1
      28     2111.022864         3    1
      30     2133.010691         3    1
      31     2143.005076         3    1}

In [110]:
for s in big_dict.keys():
    print s
    path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_Raw_data'
    path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_Raw_data/'+s+'/'
    os.makedirs(path)
    for lab in big_dict[s].keys():
        print lab
        for ph in big_dict[s][lab].keys():
            print ph
            for val in big_dict[s][lab][ph].keys():
                print val
                filename = s+'_'+lab+'_'+ph+'_'+val+'.txt'
                pathfile = path+filename
                big_dict[s][lab][ph][val].to_csv(pathfile, sep='\t', header=False, index=False)

s_02009
Neg
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
dec_ctch_onset
catch
Word
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
dec_ctch_onset
catch
Pos
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
dec_ctch_onset
catch
s_02003
Neg
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
dec_ctch_onset
catch
Word
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
dec_ctch_onset
catch
Pos
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
dec_ctch_onset
catch
s_02002
Neg
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
dec_ctch_onset
catch
Word
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
dec_ctch_onset
catch
Pos
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
dec_ctch_onset
catch
s_02001
Neg
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
dec_ctch_onset
catch
Word
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
dec_ctch_onset
catch
Pos
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
dec_ctch_onset
catch
s_02007
Neg
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
dec_ctch_onset
catch
Word
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
dec_ctch_onset
catch
Pos
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
dec_ctch_onset
catch
s_02006
Neg
cons
q1
q3
q2
q4
dec
q1
q3
q2
q4
dec_ctch_onset
catch
Word
cons
q1
q3
q2
