In [1]:
#Opened with --pylab flag
#Need to create code to analyze piot data
import pandas as pd
import numpy as np
from scipy import io
import os
import glob

In [2]:
## Laptop
#filepath = '/Users/frankkanayet/Dropbox/NLineExperiment/PilotData'
#filepath = '/Users/frankkanayet/Dropbox/NLineExperiment/PilotData/test3s'
#filepath = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data'

## Desktop
#filepath = '/Users/frankanayet/Dropbox/NLineExperiment/Data'
filepath = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/NLine-Space/NLine'
os.chdir(filepath)

In [3]:
print 'Pandas version ' + pd.__version__

Pandas version 0.16.2


In [4]:
filenames = glob.glob('Nline_*.mat')
print filenames
#index to isolate subj numbers
data_dict = {}
for i in filenames:
    id1 = filenames[0].find('_') + 1
    id2 = filenames[0].find('-')
    sub_nbr = i[id1:id2]
    sub_name = i
    s_id = 's_'+sub_nbr
    data_dict[s_id] = io.loadmat(sub_name)

#sub_name = filenames[0] #This will be changed to a loop for all subjects later
#mat = io.loadmat(sub_name)
data_dict.keys()

['Nline_03001-Oct1315a.mat', 'Nline_03003-Nov0215a.mat', 'Nline_03004-Oct2915corr.mat', 'Nline_03005-Nov0915a.mat', 'Nline_03006-Nov1215a.mat']


['s_03001', 's_03003', 's_03004', 's_03005', 's_03006']

In [5]:
sub_ex = data_dict.keys()[0]

In [6]:
#data_dict['s_00011']['p']

In [7]:
#for i in data_dict:
#    data_dict[i].pop('__header__')
#    data_dict[i].pop('__version__')
#    data_dict[i].pop('__globals__')
#data_dict['s_00011'].keys()

In [8]:
## The indexes of zeros are as follows [0][0][x][y][z][0] The x y z are the 3 dimensions of the data 3d matrix the zeros are padding
data_dict[sub_ex]['p']['NlineResults'][0][0][0][5][0][0]
len(data_dict[sub_ex]['p']['NlineResults'][0][0][:])

33

In [9]:
data_dict[sub_ex]['p'].dtype.names

('ramp_up',
 'Mean_ITI',
 'Mean_hold',
 'decision',
 'consider',
 'runs',
 'nStim',
 'ntasks',
 'tasks',
 'trialSecs',
 'vDistCM',
 'screenWidthCM',
 'usedScreenSizeDeg',
 'lineLengthDeg',
 'NlineResults',
 'time_Runs',
 'task_transition',
 'ppc_adjust',
 'lineLength',
 'start_Nline',
 'finish_Nline')

In [10]:
cons_time = data_dict[sub_ex]['p']['consider'][0][0][0][0]
dec_time = data_dict[sub_ex]['p']['decision'][0][0][0][0]

In [11]:
new_dat = {}
#new_df = {}
for s in data_dict:
    tasks = ['NlineResults']
    new_dat[s]={}
    #new_df[s] = {}
    for task in tasks:
        dat = data_dict[s]['p'][task]
        num_fields = len(data_dict[s]['p'][task][0][0][0])
        dat_names = []
        for k in range(0,num_fields):
            dat_names.append(dat[0][0][0][k][0][0])
        new_dat[s][task] = {}
        runs = data_dict[s]['p']['runs'][0][0][0][0]
        for run in range(0,runs):
            run_name = 'run'+str(run+1)
            new_dat[s][task][run_name] = {}
            for i in range(0,len(dat_names)):
                new_dat[s][task][run_name][dat_names[i]] = []
                for j in range(0,len(dat[0][0][:])-1):
                    if dat_names[i] == 'catch_probe':
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run])
                    elif dat_names[i] == 'Probe':
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run][0])
                    else:
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run][0])
#legible access to the data
Nline = 'NlineResults' #numberline

In [12]:
data_dict[s]['p'][task][0][0][1][i][run][0]

array([ 24.50019515])

In [13]:
new_dat[sub_ex]['NlineResults']['run1'].keys()

[u'Slow',
 u'Line_pct',
 u'iti',
 u'cursor_pos',
 u'ITI_onset_real',
 u'ITI_onset',
 u'RT',
 u'decision_end',
 u'decision_onset_real',
 u'decision_end_real',
 u'Correct',
 u'Wrong',
 u'BadPress',
 u'Press',
 u'Response',
 u'Acc',
 u'Task',
 u'Trial',
 u'Points',
 u'Error',
 u'catch',
 u'hold',
 u'Block',
 u'Probe',
 u'consider_onset_real',
 u'consider_onset',
 u'decision_onset',
 u'hold_onset_real',
 u'hold_onset']

In [14]:
new_dat[sub_ex]['NlineResults']['run1']['Error']

[array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([1], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([1], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([1], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8),
 array([1], dtype=uint8),
 array([0], dtype=uint8),
 array([0], dtype=uint8)]

In [15]:
subj = data_dict.keys()
tasks = [Nline]
tuples = []
rows = len(data_dict[sub_ex]['p'][Nline][0][0][:])-1
for s in subj:
    runs = new_dat[s]['NlineResults'].keys()
    for run in runs:
        for i in range(0,rows):
            tuples.append((s, run, i))
len(tuples)
#iterables = [subj,tasks,runs]
indexes = pd.MultiIndex.from_tuples(tuples, names=['Subj', 'Run', 'Trial'])
nline_cols = len(new_dat[sub_ex][Nline]['run1'].keys())

In [16]:
indexes[90]

('s_03001', 'run2', 26)

In [17]:
indexes[1][1]

'run1'

In [18]:
varnames = new_dat[sub_ex][Nline]['run1'].keys()
varnames[24]

u'consider_onset_real'

In [19]:
len(indexes)

640

In [20]:
# Code empty cells of probes and catch_probes as Nan
Dic_list = []
probes = ['catch_probe']
for data in indexes:
    temp_dict = {}
    for var in varnames:
        if len(new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]]) == 0:
            new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]] = np.array([np.nan])
        temp_dict[var] = new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]][0]
    Dic_list.append(temp_dict)

In [21]:
#Create dataframe
nline_df = pd.DataFrame(Dic_list, index=indexes)
sum(nline_df.loc[sub_ex].loc['run1'].iloc[0:48]['catch'])

8.0

In [22]:
nline_df.loc[sub_ex].loc['run4'].iloc[0:10]['Line_pct']

Trial
0    0.74
1    0.60
2    0.33
3    0.93
4    0.07
5    0.85
6    0.45
7    0.28
8    0.65
9    0.09
Name: Line_pct, dtype: float64

In [23]:
nline_df.index.names = ['Subject', 'Run', 'Trial']
nline_df.index.names

FrozenList([u'Subject', u'Run', u'Trial'])

In [24]:
#test = nline_df['Probe']
#for i in range(0,len(test)):
#    test[i] = np.ravel(test[i])
#    test[i] = test[i][0]
#nline_df['Probe'] = test
#nline_df['Probe']

### Create Stim Labels

In [25]:
#now nline
#nline_df['Num'] = nline_df['Num'].map('{:.0f}'.format)
#nline_df['Denom'] = nline_df['Denom'].map('{:.0f}'.format)
#nline_df['Stim'] = nline_df['Num']+'/'+nline_df['Denom']
#nline_df['Stim']

In [26]:
nline_df.columns

Index([                u'Acc',            u'BadPress',               u'Block',
                   u'Correct',               u'Error',           u'ITI_onset',
            u'ITI_onset_real',            u'Line_pct',              u'Points',
                     u'Press',               u'Probe',                  u'RT',
                  u'Response',                u'Slow',                u'Task',
                     u'Trial',               u'Wrong',               u'catch',
            u'consider_onset', u'consider_onset_real',          u'cursor_pos',
              u'decision_end',   u'decision_end_real',      u'decision_onset',
       u'decision_onset_real',                u'hold',          u'hold_onset',
           u'hold_onset_real',                 u'iti'],
      dtype='object')

In [27]:
#Make task as string
nline_df['Task'] = nline_df['Task'].astype(str)
nline_df['Task'][nline_df['Task']=='1.0'] = 'Pos'
nline_df['Task'][nline_df['Task']=='2.0'] = 'Neg'
nline_df['Task'][nline_df['Task']=='3.0'] = 'Word'
nline_df['Task'].iloc[16]

/Users/frankanayet/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/frankanayet/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/frankanayet/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


'Pos'

In [28]:
nline_df['Task']

Subject  Run   Trial
s_03001  run1  0        Pos
               1        Pos
               2        Pos
               3        Pos
               4        Pos
               5        Pos
               6        Pos
               7        Pos
               8        Pos
               9        Pos
               10       Pos
               11       Pos
               12       Pos
               13       Pos
               14       Pos
               15       Pos
               16       Pos
               17       Pos
               18       Pos
               19       Pos
               20       Pos
               21       Pos
               22       Pos
               23       Pos
               24       Pos
               25       Pos
               26       Pos
               27       Pos
               28       Pos
               29       Pos
                       ... 
s_03006  run4  2        Pos
               3        Pos
               4        Pos
               5        Pos

In [29]:
nline_df['Dist0'] = abs(nline_df['Line_pct'] - 0)
nline_df['Dist100'] = abs(nline_df['Line_pct'] - 1)
nline_df['Dist50'] = abs(nline_df['Line_pct'] - 0.5)
nline_df['LandmarkDist'] = nline_df[['Dist0','Dist100','Dist50']].min(axis=1) 
nline_df['LandmarkDist']

Subject  Run   Trial
s_03001  run1  0        0.14
               1        0.07
               2        0.15
               3        0.05
               4        0.07
               5        0.17
               6        0.24
               7        0.23
               8        0.09
               9        0.09
               10       0.07
               11       0.15
               12       0.10
               13       0.11
               14       0.22
               15       0.21
               16       0.24
               17       0.10
               18       0.07
               19       0.09
               20       0.07
               21       0.23
               22       0.15
               23       0.15
               24       0.07
               25       0.14
               26       0.09
               27       0.11
               28       0.21
               29       0.17
                        ... 
s_03006  run4  2        0.23
               3        0.15
               4      

# Create Onset Files

In [30]:
nline_df['Missed'] = 0

In [31]:
nline_df['Missed'][(nline_df.catch < 1) & (nline_df.Error == 1)] = 1
nline_df[(nline_df.Missed == 1)][['Error', 'Trial', 'catch', 'Correct', 'Response']]

/Users/frankanayet/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


Error  Trial  catch  Correct  Response
Subject Run  Trial                                        
s_03001 run1 6          1      7      0        2         1
             13         1     14      0        1         2
             18         1      3      0        2         1
             29         1     14      0        1         2
        run3 4          1      5      0        1         2
             6          1      7      0        1         2
             8          1      9      0        1         2
             11         1     12      0        2         1
             16         1      1      0        2         1
        run2 5          1      6      0        1         2
             20         1      5      0        1         2
             23         1      8      0        2         1
             25         1     10      0        1         2
        run4 5          1      6      0        2         1
             8          1      9      0        1         2
             13         1     14      0        1         0
             14         1     15      0        1         2
             29         1     14      0        1         2
             31         1     16      0        1         2
s_03003 run1 2          1      3      0        2         1
             3          1      4      0        1         2
             8          1      9      0        1         2
        run3 15         1     16      0        1         0
s_03004 run1 12         1     13      0        1         0
             19         1      4      0        2         1
             21         1      6      0        2         0
             24         1      9      0        2         1
             25         1     10      0        2         1
             28         1     13      0        2         1
             30         1     15      0        1         0
...                   ...    ...    ...      ...       ...
s_03006 run1 26         1     11      0        2         1
             28         1     13      0        2         1
             31         1     16      0        1         2
        run3 1          1      2      0        1         2
             2          1      3      0        1         2
             4          1      5      0        1         2
             13         1     14      0        1         2
             15         1     16      0        2         1
             23         1      8      0        1         2
        run2 1          1      2      0        1         2
             3          1      4      0        1         2
             6          1      7      0        2         1
             7          1      8      0        1         2
             8          1      9      0        2         1
             9          1     10      0        1         2
             10         1     11      0        1         2
             12         1     13      0        2         1
             14         1     15      0        2         1
             18         1      3      0        1         2
             19         1      4      0        2         1
             20         1      5      0        2         1
             22         1      7      0        1         2
             23         1      8      0        1         2
             26         1     11      0        2         1
             27         1     12      0        2         1
             30         1     15      0        1         2
        run4 4          1      5      0        1         2
             5          1      6      0        1         0
             9          1     10      0        1         2
             23         1      8      0        1         2

[96 rows x 5 columns]

In [59]:
import string
#vals = ['q1','q2','q3','q4']
#val_dict = {'q1':[0,0.25],'q2':[0.25,0.5],'q3':[0.5,0.75],'q4':[0.75,1]}
#tasks = nline_df.groupby('Task')
#labels = tasks.indices.keys()
#tasks = nline_df.groupby('Task')
#labels = tasks.indices.keys()
phase = ['cons', 'dec']
#dec_ctch_onset = {}
big_dict = {}
# Breaks always happen at the same time in the sequence
break_onset = [[182, 6, 1]]
for s in nline_df.index.levels[0]:
    print s
    big_dict[s] = {}
    #dec_ctch_onset[s] = {}
    for r in nline_df.index.levels[1]:
        #print r
        big_dict[s][r] = {}
        ctch = nline_df.loc[s].loc[r]['catch']
        if len(nline_df.loc[s].loc[r]['hold']) == 0:
            hold = 2.5
        else:
            hold = min(nline_df.loc[s].loc[r]['hold'])
        dec_ctch_tmp = nline_df.loc[s].loc[r]['decision_onset_real'] - 16
        dec_ctch_tmp = dec_ctch_tmp[ctch==1]
        big_dict[s][r]['dec_ctch_onset'] = pd.DataFrame.from_items([('time',dec_ctch_tmp[dec_ctch_tmp>=0]),('duration',dec_time),('val',1)])
        cons_duration = hold + cons_time
        for ph in phase:
            if ph == 'dec':
                tmp_int = nline_df.loc[s].loc[r]['decision_onset_real'] - 16
                tmp_int = tmp_int[ctch==0]
                big_dict[s][r][ph] = pd.DataFrame.from_items([('time',tmp_int[tmp_int>=0]),('duration',dec_time),('val',1)])
            elif ph == 'cons':
                big_dict[s][r][ph] = {}
                big_dict[s][r][ph] = {}
                tmp_val = nline_df.loc[s].loc[r]['Line_pct']
                tmp_int = nline_df.loc[s].loc[r]['consider_onset_real'] - 16
                big_dict[s][r][ph] = pd.DataFrame.from_items([('time',tmp_int[tmp_int>=0]),('duration',cons_duration),('val',tmp_val)])
        big_dict[s][r]['onsets'] = pd.concat([big_dict[s][r]['cons'], big_dict[s][r]['dec']],join='outer',)
        big_dict[s][r]['onsets'] = big_dict[s][r]['onsets'].sort('time')
                    

s_03001
s_03003
s_03004
s_03005
s_03006


In [60]:
big_dict['s_03001']['run1']['cons']

time  duration   val
Trial                            
0        4.001321         3  0.36
1       12.002170         3  0.57
2       20.501453         3  0.85
3       29.501998         3  0.45
4       39.501704         3  0.93
5       51.501965         3  0.33
6       62.001350         3  0.74
7       76.501798         3  0.77
8       86.501653         3  0.09
9      101.001879         3  0.91
10     110.501895         3  0.07
11     118.001358         3  0.65
12     129.001813         3  0.60
13     142.001203         3  0.11
14     151.001251         3  0.28
15     160.502080         3  0.21
16     176.501808         3  0.74
17     188.001236         3  0.60
18     200.001810         3  0.07
19     210.502009         3  0.09
20     220.002105         3  0.57
21     228.002063         3  0.77
22     241.001309         3  0.85
23     254.001535         3  0.65
24     262.501020         3  0.93
25     277.002009         3  0.36
26     286.001884         3  0.91
27     296.001058         3  0.11
28     306.500889         3  0.21
29     315.501234         3  0.33
30     325.001973         3  0.45
31     334.001285         3  0.28

In [61]:
big_dict['s_03001']['run1']['dec']

time  duration  val
Trial                           
0        7.008680       1.5    1
2       24.009610       1.5    1
3       34.009948       1.5    1
4       44.510471       1.5    1
5       57.011000       1.5    1
6       68.511487       1.5    1
7       80.511977       1.5    1
8       92.512305       1.5    1
10     113.513379       1.5    1
12     136.014295       1.5    1
13     145.514752       1.5    1
14     154.515101       1.5    1
16     180.016169       1.5    1
17     194.500150       1.5    1
18     205.500610       1.5    1
19     213.500948       1.5    1
21     232.501743       1.5    1
22     247.002155       1.5    1
24     269.503253       1.5    1
25     280.503774       1.5    1
27     301.004615       1.5    1
29     320.005399       1.5    1
30     329.005625       1.5    1
31     338.506195       1.5    1

In [62]:
big_dict['s_03001']['run1']['onsets']

time  duration   val
Trial                            
0        4.001321       3.0  0.36
0        7.008680       1.5  1.00
1       12.002170       3.0  0.57
2       20.501453       3.0  0.85
2       24.009610       1.5  1.00
3       29.501998       3.0  0.45
3       34.009948       1.5  1.00
4       39.501704       3.0  0.93
4       44.510471       1.5  1.00
5       51.501965       3.0  0.33
5       57.011000       1.5  1.00
6       62.001350       3.0  0.74
6       68.511487       1.5  1.00
7       76.501798       3.0  0.77
7       80.511977       1.5  1.00
8       86.501653       3.0  0.09
8       92.512305       1.5  1.00
9      101.001879       3.0  0.91
10     110.501895       3.0  0.07
10     113.513379       1.5  1.00
11     118.001358       3.0  0.65
12     129.001813       3.0  0.60
12     136.014295       1.5  1.00
13     142.001203       3.0  0.11
13     145.514752       1.5  1.00
14     151.001251       3.0  0.28
14     154.515101       1.5  1.00
15     160.502080       3.0  0.21
16     176.501808       3.0  0.74
16     180.016169       1.5  1.00
17     188.001236       3.0  0.60
17     194.500150       1.5  1.00
18     200.001810       3.0  0.07
18     205.500610       1.5  1.00
19     210.502009       3.0  0.09
19     213.500948       1.5  1.00
20     220.002105       3.0  0.57
21     228.002063       3.0  0.77
21     232.501743       1.5  1.00
22     241.001309       3.0  0.85
22     247.002155       1.5  1.00
23     254.001535       3.0  0.65
24     262.501020       3.0  0.93
24     269.503253       1.5  1.00
25     277.002009       3.0  0.36
25     280.503774       1.5  1.00
26     286.001884       3.0  0.91
27     296.001058       3.0  0.11
27     301.004615       1.5  1.00
28     306.500889       3.0  0.21
29     315.501234       3.0  0.33
29     320.005399       1.5  1.00
30     325.001973       3.0  0.45
30     329.005625       1.5  1.00
31     334.001285       3.0  0.28
31     338.506195       1.5  1.00

In [63]:
big_dict['s_03001']['run1']['dec_ctch_onset']

time  duration  val
Trial                           
1       16.009037       1.5    1
9      105.513040       1.5    1
11     122.513759       1.5    1
15     164.515521       1.5    1
20     223.501384       1.5    1
23     258.002815       1.5    1
26     290.004175       1.5    1
28     309.504749       1.5    1

In [135]:
values = nline_df.Line_pct.unique()
values.sort()
values = values[~np.isnan(values)]
values

array([ 0.07,  0.09,  0.11,  0.21,  0.28,  0.33,  0.36,  0.45,  0.57,
        0.6 ,  0.65,  0.74,  0.77,  0.85,  0.91,  0.93])

In [136]:
nline_df.groupby('Line_pct').count()

Acc  BadPress  Block  Correct  Error  ITI_onset  ITI_onset_real  \
Line_pct                                                                    
0.07       36        36     36       36     36         36              36   
0.09       36        36     36       36     36         36              36   
0.11       36        36     36       36     36         36              36   
0.21       36        36     36       36     36         36              36   
0.28       36        36     36       36     36         36              36   
0.33       36        36     36       36     36         36              36   
0.36       36        36     36       36     36         36              36   
0.45       36        36     36       36     36         36              36   
0.57       36        36     36       36     36         36              36   
0.60       36        36     36       36     36         36              36   
0.65       36        36     36       36     36         36              36   
0.74       36        36     36       36     36         36              36   
0.77       36        36     36       36     36         36              36   
0.85       36        36     36       36     36         36              36   
0.91       36        36     36       36     36         36              36   
0.93       36        36     36       36     36         36              36   

          Points  Press  Probe   ...    decision_onset_real  hold  hold_onset  \
Line_pct                         ...                                            
0.07          36     36     36   ...                     36    36          36   
0.09          36     36     36   ...                     36    36          36   
0.11          36     36     36   ...                     36    36          36   
0.21          36     36     36   ...                     36    36          36   
0.28          36     36     36   ...                     36    36          36   
0.33          36     36     36   ...                     36    36          36   
0.36          36     36     36   ...                     36    36          36   
0.45          36     36     36   ...                     36    36          36   
0.57          36     36     36   ...                     36    36          36   
0.60          36     36     36   ...                     36    36          36   
0.65          36     36     36   ...                     36    36          36   
0.74          36     36     36   ...                     36    36          36   
0.77          36     36     36   ...                     36    36          36   
0.85          36     36     36   ...                     36    36          36   
0.91          36     36     36   ...                     36    36          36   
0.93          36     36     36   ...                     36    36          36   

          hold_onset_real  iti  Dist0  Dist100  Dist50  LandmarkDist  Missed  
Line_pct                                                                      
0.07                   36   36     36       36      36            36      36  
0.09                   36   36     36       36      36            36      36  
0.11                   36   36     36       36      36            36      36  
0.21                   36   36     36       36      36            36      36  
0.28                   36   36     36       36      36            36      36  
0.33                   36   36     36       36      36            36      36  
0.36                   36   36     36       36      36            36      36  
0.45                   36   36     36       36      36            36      36  
0.57                   36   36     36       36      36            36      36  
0.60                   36   36     36       36      36            36      36  
0.65                   36   36     36       36      36            36      36  
0.74                   36   36     36       36      36            36      36  
0.77                   36   36     36       36      36    

In [137]:
tasks = nline_df.Task.unique()
tasks = tasks[tasks!='nan']
tasks

array(['Pos'], dtype=object)

In [138]:
big_dict['s_03001']['run1']['cons'][big_dict['s_03001']['run1']['cons']['val']==0.07]

time  duration   val
Trial                            
10     110.501895         3  0.07
18     200.001810         3  0.07

In [139]:
big_dict['s_03001']['run1']['cons'][big_dict['s_03001']['run1']['cons']['val']==0.07].index.tolist()

[10, 18]

In [140]:
big_index_dict = {}
for s in big_dict.keys():
    print s
    big_index_dict[s] = {}
    #dec_ctch_onset[s] = {}
    for value in values:
        print value
        big_index_dict[s][str(value)] = []
        for r in big_dict[s].keys():
            print r
            tmp_trial = big_dict[s][r]['cons'][big_dict[s][r]['cons']['val']==value].index.tolist()
            print tmp_trial
            big_index_dict[s][str(value)].append(tmp_trial)

s_03001
0.07
run1
[10, 18]
run3
[12, 25]
run2
[12, 27]
run4
[4, 16]
0.09
run1
[8, 19]
run3
[15, 26]
run2
[4, 16]
run4
[9, 19]
0.11
run1
[13, 27]
run3
[10, 27]
run2
[9, 24]
run4
[13, 27]
0.21
run1
[15, 28]
run3
[1, 29]
run2
[15, 30]
run4
[14, 29]
0.28
run1
[14, 31]
run3
[5, 30]
run2
[5, 23]
run4
[7, 30]
0.33
run1
[5, 29]
run3
[6, 23]
run2
[8, 31]
run4
[2, 31]
0.36
run1
[0, 25]
run3
[4, 28]
run2
[1, 22]
run4
[15, 25]
0.45
run1
[3, 30]
run3
[2, 20]
run2
[7, 19]
run4
[6, 18]
0.57
run1
[1, 20]
run3
[9, 24]
run2
[10, 17]
run4
[12, 21]
0.6
run1
[12, 17]
run3
[7, 21]
run2
[3, 28]
run4
[1, 28]
0.65
run1
[11, 23]
run3
[0, 19]
run2
[13, 25]
run4
[8, 26]
0.74
run1
[6, 16]
run3
[11, 22]
run2
[11, 21]
run4
[0, 23]
0.77
run1
[7, 21]
run3
[13, 16]
run2
[14, 18]
run4
[11, 24]
0.85
run1
[2, 22]
run3
[8, 18]
run2
[6, 29]
run4
[5, 17]
0.91
run1
[9, 26]
run3
[3, 31]
run2
[0, 26]
run4
[10, 20]
0.93
run1
[4, 24]
run3
[14, 17]
run2
[2, 20]
run4
[3, 22]
s_03003
0.07
run1
[4, 16]
run3
[15, 17]
run2
[14, 27]
run

In [141]:
big_index_dict['s_03003']

{'0.07': [[4, 16], [15, 17], [14, 27], []],
 '0.09': [[1, 21], [5, 24], [7, 21], []],
 '0.11': [[14, 23], [12, 20], [3, 30], []],
 '0.21': [[10, 25], [13, 19], [9, 26], []],
 '0.28': [[6, 29], [7, 22], [10, 24], []],
 '0.33': [[7, 19], [6, 23], [6, 17], []],
 '0.36': [[8, 28], [3, 31], [1, 20], []],
 '0.45': [[12, 22], [10, 27], [8, 25], []],
 '0.57': [[11, 24], [14, 26], [0, 22], []],
 '0.6': [[13, 27], [9, 30], [15, 29], []],
 '0.65': [[2, 30], [0, 28], [2, 19], []],
 '0.74': [[9, 26], [2, 25], [13, 23], []],
 '0.77': [[15, 31], [8, 21], [11, 16], []],
 '0.85': [[3, 18], [4, 18], [4, 18], []],
 '0.91': [[0, 20], [11, 29], [12, 28], []],
 '0.93': [[5, 17], [1, 16], [5, 31], []]}

In [142]:
for s in big_index_dict:
    for val in big_index_dict[s].keys():
        big_index_dict[s][val] = [item for sublist in big_index_dict[s][val] for item in sublist]

In [143]:
big_index_dict['s_03001']

{'0.07': [10, 18, 12, 25, 12, 27, 4, 16],
 '0.09': [8, 19, 15, 26, 4, 16, 9, 19],
 '0.11': [13, 27, 10, 27, 9, 24, 13, 27],
 '0.21': [15, 28, 1, 29, 15, 30, 14, 29],
 '0.28': [14, 31, 5, 30, 5, 23, 7, 30],
 '0.33': [5, 29, 6, 23, 8, 31, 2, 31],
 '0.36': [0, 25, 4, 28, 1, 22, 15, 25],
 '0.45': [3, 30, 2, 20, 7, 19, 6, 18],
 '0.57': [1, 20, 9, 24, 10, 17, 12, 21],
 '0.6': [12, 17, 7, 21, 3, 28, 1, 28],
 '0.65': [11, 23, 0, 19, 13, 25, 8, 26],
 '0.74': [6, 16, 11, 22, 11, 21, 0, 23],
 '0.77': [7, 21, 13, 16, 14, 18, 11, 24],
 '0.85': [2, 22, 8, 18, 6, 29, 5, 17],
 '0.91': [9, 26, 3, 31, 0, 26, 10, 20],
 '0.93': [4, 24, 14, 17, 2, 20, 3, 22]}

In [144]:
from nilearn import image
import nibabel

In [145]:
neuro_filepath = '/fMRI/NLine-Space/'
os.chdir(neuro_filepath)

In [146]:
pwd

u'/fMRI/NLine-Space'

In [147]:
dat_files = glob.glob('s_030??/N_run?_AllOnsets.feat/betaseries/ev1*.nii.gz')
dat_files

['s_03001/N_run1_AllOnsets.feat/betaseries/ev1_LSS.nii.gz',
 's_03001/N_run2_AllOnsets.feat/betaseries/ev1_LSS.nii.gz',
 's_03001/N_run3_AllOnsets.feat/betaseries/ev1_LSS.nii.gz',
 's_03001/N_run4_AllOnsets.feat/betaseries/ev1_LSS.nii.gz',
 's_03003/N_run1_AllOnsets.feat/betaseries/ev1_LSS.nii.gz',
 's_03003/N_run2_AllOnsets.feat/betaseries/ev1_LSS.nii.gz',
 's_03003/N_run3_AllOnsets.feat/betaseries/ev1_LSS.nii.gz',
 's_03004/N_run1_AllOnsets.feat/betaseries/ev1_LSS.nii.gz',
 's_03004/N_run2_AllOnsets.feat/betaseries/ev1_LSS.nii.gz',
 's_03004/N_run3_AllOnsets.feat/betaseries/ev1_LSS.nii.gz',
 's_03005/N_run1_AllOnsets.feat/betaseries/ev1_LSS.nii.gz',
 's_03005/N_run2_AllOnsets.feat/betaseries/ev1_LSS.nii.gz',
 's_03005/N_run3_AllOnsets.feat/betaseries/ev1_LSS.nii.gz',
 's_03005/N_run4_AllOnsets.feat/betaseries/ev1_LSS.nii.gz',
 's_03006/N_run1_AllOnsets.feat/betaseries/ev1_LSS.nii.gz',
 's_03006/N_run2_AllOnsets.feat/betaseries/ev1_LSS.nii.gz',
 's_03006/N_run3_AllOnsets.feat/betaseri

In [157]:
dict_files = {}
for i in dat_files:
    id1 = 0
    id2 = dat_files[0].find('/')
    id3 = id2+3
    sub_nbr = i[id1:id2]
    run_nbr = i[id3:id3+4]
    dict_files[sub_nbr] = {}

In [158]:
for i in dat_files:
    id1 = 0
    id2 = dat_files[0].find('/')
    id3 = id2+3
    sub_nbr = i[id1:id2]
    run_nbr = i[id3:id3+4]
    dict_files[sub_nbr][run_nbr] = [i]

In [159]:
dict_files

{'s_03001': {'run1': ['s_03001/N_run1_AllOnsets.feat/betaseries/ev1_LSS.nii.gz'],
  'run2': ['s_03001/N_run2_AllOnsets.feat/betaseries/ev1_LSS.nii.gz'],
  'run3': ['s_03001/N_run3_AllOnsets.feat/betaseries/ev1_LSS.nii.gz'],
  'run4': ['s_03001/N_run4_AllOnsets.feat/betaseries/ev1_LSS.nii.gz']},
 's_03003': {'run1': ['s_03003/N_run1_AllOnsets.feat/betaseries/ev1_LSS.nii.gz'],
  'run2': ['s_03003/N_run2_AllOnsets.feat/betaseries/ev1_LSS.nii.gz'],
  'run3': ['s_03003/N_run3_AllOnsets.feat/betaseries/ev1_LSS.nii.gz']},
 's_03004': {'run1': ['s_03004/N_run1_AllOnsets.feat/betaseries/ev1_LSS.nii.gz'],
  'run2': ['s_03004/N_run2_AllOnsets.feat/betaseries/ev1_LSS.nii.gz'],
  'run3': ['s_03004/N_run3_AllOnsets.feat/betaseries/ev1_LSS.nii.gz']},
 's_03005': {'run1': ['s_03005/N_run1_AllOnsets.feat/betaseries/ev1_LSS.nii.gz'],
  'run2': ['s_03005/N_run2_AllOnsets.feat/betaseries/ev1_LSS.nii.gz'],
  'run3': ['s_03005/N_run3_AllOnsets.feat/betaseries/ev1_LSS.nii.gz'],
  'run4': ['s_03005/N_run4_All

In [151]:
values = [str(x) for x in values]
values

['0.07',
 '0.09',
 '0.11',
 '0.21',
 '0.28',
 '0.33',
 '0.36',
 '0.45',
 '0.57',
 '0.6',
 '0.65',
 '0.74',
 '0.77',
 '0.85',
 '0.91',
 '0.93']

In [152]:
runs = ['run1','run2','run3','run4']
for s in big_index_dict.keys():
    print s
    for r in range(0,len(big_index_dict[s]['0.07'])/2):
        print r
        tmp_list = []
        for number in values:
            tmp_list.append(big_index_dict[s][number][r*2])
            tmp_list.append(big_index_dict[s][number][(r*2)+1])
        big_index_dict[s][runs[r]] = tmp_list

s_03001
0
1
2
3
s_03003
0
1
2
s_03004
0
1
2
s_03005
0
1
2
3
s_03006
0
1
2
3


In [154]:
big_index_dict['s_03001']

{'0.07': [10, 18, 12, 25, 12, 27, 4, 16],
 '0.09': [8, 19, 15, 26, 4, 16, 9, 19],
 '0.11': [13, 27, 10, 27, 9, 24, 13, 27],
 '0.21': [15, 28, 1, 29, 15, 30, 14, 29],
 '0.28': [14, 31, 5, 30, 5, 23, 7, 30],
 '0.33': [5, 29, 6, 23, 8, 31, 2, 31],
 '0.36': [0, 25, 4, 28, 1, 22, 15, 25],
 '0.45': [3, 30, 2, 20, 7, 19, 6, 18],
 '0.57': [1, 20, 9, 24, 10, 17, 12, 21],
 '0.6': [12, 17, 7, 21, 3, 28, 1, 28],
 '0.65': [11, 23, 0, 19, 13, 25, 8, 26],
 '0.74': [6, 16, 11, 22, 11, 21, 0, 23],
 '0.77': [7, 21, 13, 16, 14, 18, 11, 24],
 '0.85': [2, 22, 8, 18, 6, 29, 5, 17],
 '0.91': [9, 26, 3, 31, 0, 26, 10, 20],
 '0.93': [4, 24, 14, 17, 2, 20, 3, 22],
 'run1': [10,
  18,
  8,
  19,
  13,
  27,
  15,
  28,
  14,
  31,
  5,
  29,
  0,
  25,
  3,
  30,
  1,
  20,
  12,
  17,
  11,
  23,
  6,
  16,
  7,
  21,
  2,
  22,
  9,
  26,
  4,
  24],
 'run2': [12,
  25,
  15,
  26,
  10,
  27,
  1,
  29,
  5,
  30,
  6,
  23,
  4,
  28,
  2,
  20,
  9,
  24,
  7,
  21,
  0,
  19,
  11,
  22,
  13,
  16,
  8,
 

In [160]:
def sort_run(s,r):
    tmp_img = nibabel.load(dict_files[s][r][0])
    tmp_data = tmp_img.get_data()
    myorder = big_index_dict[s][r]
    img_shape = tmp_img.shape
    print 'img_shape', img_shape
    cor_img_shape = [img_shape[0],img_shape[1],img_shape[2],len(myorder)]
    print 'cor_img_shape', cor_img_shape
    zero_img = np.zeros(cor_img_shape)
    for x in range(0,len(myorder)):
        zero_img[:,:,:,x] = tmp_data[:,:,:,myorder[x]]
    nii = nibabel.Nifti1Image(zero_img,header=tmp_img.get_header(),affine=tmp_img.get_affine())
    out_path = s+'/N_'+r+'_AllOnsets.feat/betaseries/'
    out_name = s+'_N_'+r+'_sorted.nii.gz'
    out_pathname = out_path + out_name
    nibabel.save(nii,out_pathname)

In [161]:
sort_run('s_03001','run1')

img_shape (110, 110, 62, 32)
cor_img_shape [110, 110, 62, 32]


## Save Files

In [162]:
runs = ['run1','run2','run3','run4']
for s in big_index_dict.keys():
    print s
    for r in range(0,len(big_index_dict[s]['0.07'])/2):
        print runs[r]
        sort_run(s,runs[r])

s_03001
run1
img_shape (110, 110, 62, 32)
cor_img_shape [110, 110, 62, 32]
run2
img_shape (110, 110, 62, 32)
cor_img_shape [110, 110, 62, 32]
run3
img_shape (110, 110, 62, 32)
cor_img_shape [110, 110, 62, 32]
run4
img_shape (110, 110, 62, 32)
cor_img_shape [110, 110, 62, 32]
s_03003
run1
img_shape (110, 110, 62, 32)
cor_img_shape [110, 110, 62, 32]
run2
img_shape (110, 110, 62, 32)
cor_img_shape [110, 110, 62, 32]
run3
img_shape (110, 110, 62, 32)
cor_img_shape [110, 110, 62, 32]
s_03004
run1
img_shape (110, 110, 62, 32)
cor_img_shape [110, 110, 62, 32]
run2
img_shape (110, 110, 62, 32)
cor_img_shape [110, 110, 62, 32]
run3
img_shape (110, 110, 62, 32)
cor_img_shape [110, 110, 62, 32]
s_03005
run1
img_shape (110, 110, 62, 32)
cor_img_shape [110, 110, 62, 32]
run2
img_shape (110, 110, 62, 32)
cor_img_shape [110, 110, 62, 32]
run3
img_shape (110, 110, 62, 32)
cor_img_shape [110, 110, 62, 32]
run4
img_shape (110, 110, 62, 32)
cor_img_shape [110, 110, 62, 32]
s_03006
run1
img_shape (110, 1