In [1]:
#Opened with --pylab flag
#Need to create code to analyze piot data
import pandas as pd
import numpy as np
from scipy import io
import os
import glob

In [4]:
## Laptop
#filepath = '/Users/frankkanayet/Dropbox/NLineExperiment/PilotData'
#filepath = '/Users/frankkanayet/Dropbox/NLineExperiment/PilotData/test3s'
#filepath = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data'

## Desktop
#filepath = '/Users/frankanayet/Dropbox/NLineExperiment/Data'
filepath = '/Users/frankanayet/Google Drive/NLineData/Beh_Data'
os.chdir(filepath)

In [5]:
print 'Pandas version ' + pd.__version__

Pandas version 0.15.2


In [6]:
filenames = glob.glob('Nline_*.mat')
print filenames
#index to isolate subj numbers
data_dict = {}
for i in filenames:
    id1 = filenames[0].find('_') + 1
    id2 = filenames[0].find('-')
    sub_nbr = i[id1:id2]
    sub_name = i
    s_id = 's_'+sub_nbr
    data_dict[s_id] = io.loadmat(sub_name)

#sub_name = filenames[0] #This will be changed to a loop for all subjects later
#mat = io.loadmat(sub_name)
data_dict.keys()

['Nline_02001-Mar1615.mat', 'Nline_02002-Mar1915.mat', 'Nline_02003-Mar2015a.mat', 'Nline_02004-Mar2315a.mat', 'Nline_02005-Mar2315a.mat', 'Nline_02006-Mar2315a.mat', 'Nline_02007-Mar2415a.mat', 'Nline_02009-Mar2615a.mat', 'Nline_02010-Mar2615a.mat', 'Nline_02011-Mar2615a.mat', 'Nline_02012-Apr0215a.mat', 'Nline_02014-Apr0315a.mat', 'Nline_02015Apr2715a.mat', 'Nline_02016-Apr2715a.mat', 'Nline_02017-Apr2815a.mat', 'Nline_02018-Apr2815a.mat', 'Nline_02019-Apr2915a.mat', 'Nline_02020-May1815a.mat', 'Nline_02021-May2515a.mat', 'Nline_02022-May2515a.mat', 'Nline_02023-May2715a.mat', 'Nline_02024-May2815a.mat', 'Nline_02027-Jun0115a.mat']


['s_02009',
 's_02003',
 's_02002',
 's_02001',
 's_02007',
 's_02006',
 's_02005',
 's_02004',
 's_02018',
 's_02019',
 's_02010',
 's_02011',
 's_02012',
 's_02014',
 's_02015',
 's_02016',
 's_02017',
 's_02024',
 's_02027',
 's_02021',
 's_02020',
 's_02023',
 's_02022']

In [7]:
sub_ex = data_dict.keys()[0]

In [8]:
#data_dict['s_00011']['p']

In [9]:
#for i in data_dict:
#    data_dict[i].pop('__header__')
#    data_dict[i].pop('__version__')
#    data_dict[i].pop('__globals__')
#data_dict['s_00011'].keys()

In [10]:
## The indexes of zeros are as follows [0][0][x][y][z][0] The x y z are the 3 dimensions of the data 3d matrix the zeros are padding
data_dict[sub_ex]['p']['NlineResults'][0][0][0][5][0][0]
len(data_dict[sub_ex]['p']['NlineResults'][0][0][:])

49

In [11]:
data_dict[sub_ex]['p'].dtype.names

('ramp_up',
 'Mean_ITI',
 'Mean_hold',
 'decision',
 'consider',
 'runs',
 'nStim',
 'ntasks',
 'tasks',
 'trialSecs',
 'lineLength',
 'speed',
 'run_order',
 'NlineResults',
 'time_Runs',
 'task_transition',
 'start_Nline',
 'finish_Nline')

In [12]:
cons_time = data_dict[sub_ex]['p']['consider'][0][0][0][0]
dec_time = data_dict[sub_ex]['p']['decision'][0][0][0][0]

In [13]:
new_dat = {}
#new_df = {}
for s in data_dict:
    tasks = ['NlineResults']
    new_dat[s]={}
    #new_df[s] = {}
    for task in tasks:
        dat = data_dict[s]['p'][task]
        num_fields = len(data_dict[s]['p'][task][0][0][0])
        dat_names = []
        for k in range(0,num_fields):
            dat_names.append(dat[0][0][0][k][0][0])
        new_dat[s][task] = {}
        runs = data_dict[s]['p']['runs'][0][0][0][0]
        for run in range(0,runs):
            run_name = 'run'+str(run+1)
            new_dat[s][task][run_name] = {}
            for i in range(0,len(dat_names)):
                new_dat[s][task][run_name][dat_names[i]] = []
                for j in range(0,len(dat[0][0][:])-1):
                    if dat_names[i] == 'catch_probe':
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run])
                    elif dat_names[i] == 'Probe':
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run][0])
                    else:
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run][0][0])
#legible access to the data
Nline = 'NlineResults' #numberline

In [14]:
new_dat[sub_ex]['NlineResults']['run1'].keys()

[u'Slow',
 u'Line_pct',
 u'iti',
 u'TestX',
 u'ITI_onset_real',
 u'consider_onset_real',
 u'ITI_onset',
 u'RT',
 u'hold',
 u'decision_end',
 u'decision_onset_real',
 u'RTHold',
 u'decision_end_real',
 u'Correct',
 u'Wrong',
 u'BadPress',
 u'consider_onset',
 u'Response',
 u'Task',
 u'Trial',
 u'Points',
 u'Error',
 u'catch',
 u'mouse_pos',
 u'Block',
 u'catch_probe',
 u'Probe',
 u'hold_onset',
 u'Move',
 u'decision_onset',
 u'hold_onset_real',
 u'Click']

In [15]:
new_dat[sub_ex]['NlineResults']['run1']['Probe']

[array([57], dtype=uint8),
 array([77], dtype=uint8),
 array([3], dtype=uint8),
 array([21], dtype=uint8),
 array([60], dtype=uint8),
 array([28], dtype=uint8),
 array([85], dtype=uint8),
 array([74], dtype=uint8),
 array([33], dtype=uint8),
 array([7], dtype=uint8),
 array([90], dtype=uint8),
 array([36], dtype=uint8),
 array([11], dtype=uint8),
 array([45], dtype=uint8),
 array([98], dtype=uint8),
 array([65], dtype=uint8),
 array([70], dtype=uint8),
 array([14], dtype=uint8),
 array([80], dtype=uint8),
 array([20], dtype=uint8),
 array([-58], dtype=int16),
 array([-94], dtype=int16),
 array([-86], dtype=int16),
 array([54], dtype=uint8),
 array([-44], dtype=int16),
 array([-78], dtype=int16),
 array([-10], dtype=int16),
 array([48], dtype=uint8),
 array([30], dtype=uint8),
 array([-28], dtype=int16),
 array([96], dtype=uint8),
 array([-34], dtype=int16),
 u'of',
 u'is',
 u'be',
 u'me',
 u'it',
 u'as',
 u'my',
 u'so',
 u'we',
 u'or',
 u'ox',
 u'by',
 u'am',
 u'he',
 u'do',
 u'if']

In [16]:
new_dat[sub_ex]['NlineResults']['run1']['catch_probe']

[array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), 

In [17]:
subj = data_dict.keys()
tasks = [Nline]
tuples = []
rows = len(data_dict[sub_ex]['p'][Nline][0][0][:])-1
for s in subj:
    runs = new_dat[s]['NlineResults'].keys()
    for run in runs:
        for i in range(0,rows):
            tuples.append((s, run, i))
len(tuples)
#iterables = [subj,tasks,runs]
indexes = pd.MultiIndex.from_tuples(tuples, names=['Subj', 'Run', 'Trial'])
nline_cols = len(new_dat[sub_ex][Nline]['run1'].keys())

In [18]:
indexes[90]

('s_02009', 'run3', 42)

In [19]:
indexes[1][1]

'run1'

In [20]:
varnames = new_dat[sub_ex][Nline]['run1'].keys()
varnames[24]

u'Block'

In [21]:
len(indexes)

4224

In [22]:
# Code empty cells of probes and catch_probes as Nan
Dic_list = []
probes = ['catch_probe']
for data in indexes:
    temp_dict = {}
    for var in varnames:
        if var == probes[0]:
            if len(new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]]) == 0:
                new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]] = np.array([np.nan])
            temp_dict[var] = new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]][0]
        else:
            temp_dict[var] = new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]]
    Dic_list.append(temp_dict)

In [23]:
#Create dataframe
nline_df = pd.DataFrame(Dic_list, index=indexes)
sum(nline_df.loc[sub_ex].loc['run1'].iloc[0:48]['catch'])

12

In [24]:
nline_df.loc[sub_ex].loc['run1'].iloc[0:10]['Error']

Trial
0       -0.023744
1       -0.025507
2        0.000000
3        0.000000
4       -0.027313
5        0.001938
6       -0.046035
7        0.000000
8        0.070881
9        0.026916
Name: Error, dtype: float64

In [25]:
nline_df.index.names = ['Subject', 'Run', 'Trial']
nline_df.index.names

FrozenList([u'Subject', u'Run', u'Trial'])

In [26]:
test = nline_df['Probe']
for i in range(0,len(test)):
    test[i] = np.ravel(test[i])
    test[i] = test[i][0]
nline_df['Probe'] = test
nline_df['Probe']

/Users/frankanayet/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/frankanayet/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


Subject  Run   Trial
s_02009  run1  0        57
               1        77
               2         3
               3        21
               4        60
               5        28
               6        85
               7        74
               8        33
               9         7
               10       90
               11       36
               12       11
               13       45
               14       98
...
s_02022  run4  33       -28
               34        70
               35        96
               36       -10
               37        80
               38        48
               39        54
               40       -94
               41       -34
               42       -44
               43        30
               44        20
               45       -78
               46        14
               47       -58
Name: Probe, Length: 4224, dtype: object

### Create Stim Labels

In [25]:
#now nline
#nline_df['Num'] = nline_df['Num'].map('{:.0f}'.format)
#nline_df['Denom'] = nline_df['Denom'].map('{:.0f}'.format)
#nline_df['Stim'] = nline_df['Num']+'/'+nline_df['Denom']
#nline_df['Stim']

In [26]:
nline_df.columns

Index([u'BadPress', u'Block', u'Click', u'Correct', u'Error', u'ITI_onset', u'ITI_onset_real', u'Line_pct', u'Move', u'Points', u'Probe', u'RT', u'RTHold', u'Response', u'Slow', u'Task', u'TestX', u'Trial', u'Wrong', u'catch', u'catch_probe', u'consider_onset', u'consider_onset_real', u'decision_end', u'decision_end_real', u'decision_onset', u'decision_onset_real', u'hold', u'hold_onset', u'hold_onset_real', u'iti', u'mouse_pos'], dtype='object')

In [40]:
#Make task as string
nline_df['Task'] = nline_df['Task'].astype(str)
nline_df['Task'][nline_df['Task']=='1'] = 'Pos'
nline_df['Task'][nline_df['Task']=='2'] = 'Neg'
nline_df['Task'][nline_df['Task']=='3'] = 'Word'
nline_df['Task'].iloc[16]

/Users/frankanayet/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/frankanayet/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/frankanayet/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


'Neg'

In [41]:
nline_df['Task']

Subject  Run   Trial
s_02009  run1  0        Pos
               1        Pos
               2        Pos
               3        Pos
               4        Pos
               5        Pos
               6        Pos
               7        Pos
               8        Pos
               9        Pos
               10       Pos
               11       Pos
               12       Pos
               13       Pos
               14       Pos
...
s_02022  run4  33       Neg
               34       Neg
               35       Neg
               36       Neg
               37       Neg
               38       Neg
               39       Neg
               40       Neg
               41       Neg
               42       Neg
               43       Neg
               44       Neg
               45       Neg
               46       Neg
               47       Neg
Name: Task, Length: 4224, dtype: object

In [42]:
nline_df['Dist0'] = abs(nline_df['Line_pct'] - 0)
nline_df['Dist100'] = abs(nline_df['Line_pct'] - 1)
nline_df['Dist50'] = abs(nline_df['Line_pct'] - 0.5)
nline_df['LandmarkDist'] = nline_df[['Dist0','Dist100','Dist50']].min(axis=1) 
nline_df['LandmarkDist']

Subject  Run   Trial
s_02009  run1  0        0.07
               1        0.23
               2        0.03
               3        0.21
               4        0.10
               5        0.22
               6        0.15
               7        0.24
               8        0.17
               9        0.07
               10       0.10
               11       0.14
               12       0.11
               13       0.05
               14       0.02
...
s_02022  run4  33       0.14
               34       0.15
               35       0.02
               36       0.05
               37       0.10
               38       0.24
               39       0.23
               40       0.03
               41       0.17
               42       0.22
               43       0.15
               44       0.10
               45       0.11
               46       0.07
               47       0.21
Name: LandmarkDist, Length: 4224, dtype: float64

# Create Onset Files

In [43]:
nline_df['Missed'] = 0

In [44]:
nline_df['Missed'][(nline_df.catch < 1) & (nline_df.Error == 1)] = 1
nline_df[(nline_df.Missed == 1)]['Error']

/Users/frankanayet/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


Subject  Run   Trial
s_02009  run1  22       1
s_02003  run1  0        1
               15       1
               26       1
               36       1
         run3  20       1
               23       1
         run4  1        1
s_02002  run1  9        1
               29       1
s_02001  run1  25       1
s_02007  run4  24       1
s_02006  run1  12       1
         run2  35       1
s_02005  run1  0        1
...
s_02022  run1  40       1
         run3  29       1
               47       1
         run2  3        1
               6        1
               15       1
               25       1
               37       1
               40       1
         run4  4        1
               5        1
               9        1
               14       1
               20       1
               27       1
Name: Error, Length: 162, dtype: float64

In [45]:
nline_df['Missed'][(nline_df.catch < 1) & (abs(nline_df.Error) >= 0.1)] = 1
nline_df[(nline_df.Missed == 1)]['Error']

/Users/frankanayet/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


Subject  Run   Trial
s_02009  run1  22       1.000000
               24       0.220000
s_02003  run1  0        1.000000
               15       1.000000
               26       1.000000
               36       1.000000
         run3  20       1.000000
               23       1.000000
         run4  1        1.000000
               47      -0.137533
s_02002  run1  9        1.000000
               29       1.000000
         run2  34      -0.687004
               43       0.575374
s_02001  run1  25       1.000000
...
s_02022  run3  41       0.132291
               47       1.000000
         run2  3        1.000000
               6        1.000000
               15       1.000000
               25       1.000000
               37       1.000000
               40       1.000000
         run4  4        1.000000
               5        1.000000
               9        1.000000
               14       1.000000
               20       1.000000
               27       1.000000
               34 

In [46]:
import string
tasks = nline_df.groupby('Task')
labels = tasks.indices.keys()
cons_onset_small = {}
dec_onset_small = {}
cons_onset_large = {}
dec_onset_large = {}
dec_ctch_onset = {}
miss_dec_onset = {}
# Breaks always happen at the same time in the sequence
break_onset = [[190, 6, 1],[388, 6, 1]]
for s in nline_df.index.levels[0]:
    print s
    cons_onset_small[s] = {}
    dec_onset_small[s] = {}
    cons_onset_large[s] = {}
    dec_onset_large[s] = {}
    dec_ctch_onset[s] = {}
    miss_dec_onset[s] = {}
    for r in nline_df.index.levels[1]:
        #print r
        ctch = nline_df.loc[s].loc[r]['catch']
        probe = nline_df.loc[s].loc[r]['Line_pct']
        dec_ctch_tmp = nline_df.loc[s].loc[r]['decision_onset_real'] - 16
        dec_ctch_tmp = dec_ctch_tmp[ctch==1]
        dec_ctch_onset[s][r] = pd.DataFrame.from_items([('time',dec_ctch_tmp[dec_ctch_tmp>=0]),('duration',dec_time),('val',1)])
        miss = nline_df.loc[s].loc[r]['Missed']
        miss_dec_tmp = nline_df.loc[s].loc[r]['decision_onset_real'] - 16
        miss_dec_tmp = miss_dec_tmp[miss == 1]
        miss_dec_onset[s][r] = pd.DataFrame.from_items([('time',miss_dec_tmp[miss_dec_tmp>=0]),('duration',dec_time),('val',1)])
        cons_onset_small[s][r] = {}
        dec_onset_small[s][r] = {}
        cons_onset_large[s][r] = {}
        dec_onset_large[s][r] = {}
        for lab in labels:
            #print lab
            Task = nline_df.loc[s].loc[r]['Task']
            #create time data for small and large numbers separetely
            cons_tmp_small = nline_df.loc[s].loc[r]['consider_onset_real'] - 16
            cons_tmp_small = cons_tmp_small[Task==lab]
            cons_tmp_small = cons_tmp_small[probe<0.5]
            cons_tmp_large = nline_df.loc[s].loc[r]['consider_onset_real'] - 16
            cons_tmp_large = cons_tmp_large[Task==lab]
            cons_tmp_large = cons_tmp_large[probe>0.5]
            cons_duration = nline_df.loc[s].loc[r]['hold'] + cons_time
            cons_duration = cons_duration[Task==lab]
            cons_duration_small = cons_duration[probe<0.5]
            cons_duration_large = cons_duration[probe>0.5]
            cons_onset_small[s][r][lab] = pd.DataFrame.from_items([('time',cons_tmp_small[cons_tmp_small>=0]),('duration',cons_duration_small),('val',1)])        
            cons_onset_large[s][r][lab] = pd.DataFrame.from_items([('time',cons_tmp_large[cons_tmp_large>=0]),('duration',cons_duration_large),('val',1)])
            #Now decision phase
            dec_tmp_small = nline_df.loc[s].loc[r]['decision_onset_real'] - 16
            dec_tmp_small = dec_tmp_small[ctch==0]
            dec_tmp_small = dec_tmp_small[Task==lab]
            dec_tmp_small = dec_tmp_small[probe<0.5]
            dec_tmp_small = dec_tmp_small[miss==0]
            dec_tmp_large = nline_df.loc[s].loc[r]['decision_onset_real'] - 16
            dec_tmp_large = dec_tmp_large[ctch==0]
            dec_tmp_large = dec_tmp_large[Task==lab]
            dec_tmp_large = dec_tmp_large[probe>0.5]
            dec_tmp_large = dec_tmp_large[miss==0]
            dec_duration = nline_df.loc[s].loc[r]['RT']
            dec_duration = dec_duration[ctch==0]
            dec_duration = dec_duration[Task==lab]
            dec_duration = dec_duration[miss==0]
            dec_duration_small = dec_duration[probe<0.5]
            dec_duration_large = dec_duration[probe>0.5]
            dec_onset_small[s][r][lab] = pd.DataFrame.from_items([('time',dec_tmp_small[dec_tmp_small>=0]),('duration',dec_duration_small),('val',1)])        
            dec_onset_large[s][r][lab] = pd.DataFrame.from_items([('time',dec_tmp_large[dec_tmp_large>=0]),('duration',dec_duration_large),('val',1)])

s_02001
s_02002
s_02003
s_02004
s_02005
s_02006
s_02007
s_02009
s_02010
s_02011
s_02012
s_02014
s_02015
s_02016
s_02017
s_02018
s_02019
s_02020
s_02021
s_02022
s_02023
s_02024
s_02027


In [47]:
dec_onset_small['s_02003']['run4']

{'Neg':              time  duration  val
 Trial                           
 18     229.522318  2.055193    1
 21     265.506566  1.506459    1
 22     275.023619  2.443657    1
 24     302.524333  2.545183    1
 25     315.007947  2.315157    1
 26     326.524939  2.328911    1
 28     354.025852  2.305008    1, 'Pos':              time  duration  val
 Trial                           
 34     426.521426  1.675605    1
 35     441.011482  1.968717    1
 36     452.011804  1.769862    1
 37     462.528905  2.227524    1
 40     493.513050  2.392542    1
 41     503.538130  2.096619    1, 'Word':              time  duration  val
 Trial                           
 4       56.517587  2.477587    1
 5       66.517788  1.772245    1
 6       76.510647  2.410942    1
 8      100.518719  2.409698    1
 9      111.527217  2.230540    1
 12     148.019942  2.292022    1}

In [48]:
dec_onset_large['s_02003']['run4']

{'Neg':              time  duration  val
 Trial                           
 16     206.054929  2.595699    1
 17     220.022015  1.954930    1
 20     254.506405  2.654803    1
 27     339.025428  2.143061    1
 30     373.510701  2.137307    1, 'Pos':              time  duration  val
 Trial                           
 33     413.510687  1.980480    1
 38     472.029098  1.558187    1
 44     539.514489  2.138295    1
 45     552.031222  2.364854    1
 46     568.515163  2.098409    1, 'Word':              time  duration  val
 Trial                           
 2       32.033442  2.467747    1
 7       89.501792  2.467415    1
 10     124.519309  2.278025    1
 11     137.019690  2.294532    1
 13     161.203701  1.853297    1}

In [49]:
miss_dec_onset['s_02003']['run4']

time  duration  val
Trial                           
1       18.533072         3    1
47     583.015547         3    1

## Save Files

In [50]:
tasks = {'Pos': [cons_onset_small,dec_onset_small,cons_onset_large,dec_onset_large],
         'Neg': [cons_onset_small,dec_onset_small,cons_onset_large,dec_onset_large],
         'Word': [cons_onset_small,dec_onset_small,cons_onset_large,dec_onset_large],}
runs = ['run1', 'run2', 'run3', 'run4']
for s in nline_df.index.levels[0]:
    print s
    #Desktop
    path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_SizeFull'
    path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_SizeFull/'+s+'/'
    os.makedirs(path)
    for r in nline_df.index.levels[1]:
        print r
        dec_ctch_filename = s+'_'+r+'DEC_CTCH.txt'
        dec_pathfile = path+dec_ctch_filename
        dec_ctch_onset[s][r].to_csv(dec_pathfile, sep='\t', header=False, index=False)
        dec_miss_filename = s+'_'+r+'_DEC_MISS.txt'
        dec_miss_pathfile = path+dec_miss_filename
        miss_dec_onset[s][r].to_csv(dec_miss_pathfile, sep='\t', header=False, index=False)
        for task in tasks.keys():
            print task
            dec_small_filename = s+'_'+task+'_'+r+'_'+'DEC_SM'+'.txt'
            cons_small_filename = s+'_'+task+'_'+r+'_'+'CONS_SM'+'.txt'
            dec_large_filename = s+'_'+task+'_'+r+'_'+'DEC_LG'+'.txt'
            cons_large_filename = s+'_'+task+'_'+r+'_'+'CONS_LG'+'.txt'
            dec_small_pathfile = path+dec_small_filename
            cons_small_pathfile = path+cons_small_filename
            dec_large_pathfile = path+dec_large_filename
            cons_large_pathfile = path+cons_large_filename
            tasks[task][0][s][r][task].to_csv(cons_small_pathfile, sep='\t', header=False, index=False)
            tasks[task][1][s][r][task].to_csv(dec_small_pathfile, sep='\t', header=False, index=False)
            tasks[task][2][s][r][task].to_csv(cons_large_pathfile, sep='\t', header=False, index=False)
            tasks[task][3][s][r][task].to_csv(dec_large_pathfile, sep='\t', header=False, index=False)

s_02001
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02002
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02003
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02004
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02005
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02006
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02007
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02009
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02010
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02011
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02012
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02014
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02015
run1
Neg
Word
Pos
run2
Neg
Word


In [51]:
#Save Break onset file
path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_SizeFull/'
#Desktop
break_onset = pd.DataFrame.from_items([('time',[190, 388]),('duration',[6,6]),('val',[1,1])])
break_filename = 'Break_onsets.txt'
break_pathfile = path+break_filename
break_onset.to_csv(break_pathfile, sep='\t', header=False, index=False)