## Not using RTs to modulate duration or decision and including Miss trials into the decision regressors. Dec = 3s, Cons = cons + minHold

In [1]:
#Opened with --pylab flag
#Need to create code to analyze piot data
import pandas as pd
import numpy as np
from scipy import io
import os
import glob

In [2]:
## Laptop
#filepath = '/Users/frankkanayet/Dropbox/NLineExperiment/PilotData'
#filepath = '/Users/frankkanayet/Dropbox/NLineExperiment/PilotData/test3s'
#filepath = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data'

## Desktop
#filepath = '/Users/frankanayet/Dropbox/NLineExperiment/Data'
filepath = '/Users/frankanayet/Google Drive/NLineData/Beh_Data'
os.chdir(filepath)

In [3]:
print 'Pandas version ' + pd.__version__

Pandas version 0.16.2


In [4]:
filenames = glob.glob('Nline_*.mat')
print filenames
#index to isolate subj numbers
data_dict = {}
for i in filenames:
    id1 = filenames[0].find('_') + 1
    id2 = filenames[0].find('-')
    sub_nbr = i[id1:id2]
    sub_name = i
    s_id = 's_'+sub_nbr
    data_dict[s_id] = io.loadmat(sub_name)

#sub_name = filenames[0] #This will be changed to a loop for all subjects later
#mat = io.loadmat(sub_name)
data_dict.keys()

['Nline_02001-Mar1615.mat', 'Nline_02002-Mar1915.mat', 'Nline_02003-Mar2015a.mat', 'Nline_02004-Mar2315a.mat', 'Nline_02005-Mar2315a.mat', 'Nline_02006-Mar2315a.mat', 'Nline_02007-Mar2415a.mat', 'Nline_02009-Mar2615a.mat', 'Nline_02010-Mar2615a.mat', 'Nline_02011-Mar2615a.mat', 'Nline_02012-Apr0215a.mat', 'Nline_02014-Apr0315a.mat', 'Nline_02015Apr2715a.mat', 'Nline_02016-Apr2715a.mat', 'Nline_02017-Apr2815a.mat', 'Nline_02018-Apr2815a.mat', 'Nline_02019-Apr2915a.mat', 'Nline_02020-May1815a.mat', 'Nline_02021-May2515a.mat', 'Nline_02022-May2515a.mat', 'Nline_02023-May2715a.mat', 'Nline_02024-May2815a.mat', 'Nline_02027-Jun0115a.mat']


['s_02009',
 's_02003',
 's_02002',
 's_02001',
 's_02007',
 's_02006',
 's_02005',
 's_02004',
 's_02018',
 's_02019',
 's_02010',
 's_02011',
 's_02012',
 's_02014',
 's_02015',
 's_02016',
 's_02017',
 's_02024',
 's_02027',
 's_02021',
 's_02020',
 's_02023',
 's_02022']

In [5]:
sub_ex = data_dict.keys()[0]

In [6]:
#data_dict['s_00011']['p']

In [7]:
#for i in data_dict:
#    data_dict[i].pop('__header__')
#    data_dict[i].pop('__version__')
#    data_dict[i].pop('__globals__')
#data_dict['s_00011'].keys()

In [8]:
## The indexes of zeros are as follows [0][0][x][y][z][0] The x y z are the 3 dimensions of the data 3d matrix the zeros are padding
data_dict[sub_ex]['p']['NlineResults'][0][0][0][5][0][0]
len(data_dict[sub_ex]['p']['NlineResults'][0][0][:])

49

In [9]:
data_dict[sub_ex]['p'].dtype.names

('ramp_up',
 'Mean_ITI',
 'Mean_hold',
 'decision',
 'consider',
 'runs',
 'nStim',
 'ntasks',
 'tasks',
 'trialSecs',
 'lineLength',
 'speed',
 'run_order',
 'NlineResults',
 'time_Runs',
 'task_transition',
 'start_Nline',
 'finish_Nline')

In [10]:
cons_time = data_dict[sub_ex]['p']['consider'][0][0][0][0]
dec_time = data_dict[sub_ex]['p']['decision'][0][0][0][0]

In [11]:
new_dat = {}
#new_df = {}
for s in data_dict:
    tasks = ['NlineResults']
    new_dat[s]={}
    #new_df[s] = {}
    for task in tasks:
        dat = data_dict[s]['p'][task]
        num_fields = len(data_dict[s]['p'][task][0][0][0])
        dat_names = []
        for k in range(0,num_fields):
            dat_names.append(dat[0][0][0][k][0][0])
        new_dat[s][task] = {}
        runs = data_dict[s]['p']['runs'][0][0][0][0]
        for run in range(0,runs):
            run_name = 'run'+str(run+1)
            new_dat[s][task][run_name] = {}
            for i in range(0,len(dat_names)):
                new_dat[s][task][run_name][dat_names[i]] = []
                for j in range(0,len(dat[0][0][:])-1):
                    if dat_names[i] == 'catch_probe':
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run])
                    elif dat_names[i] == 'Probe':
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run][0])
                    else:
                        new_dat[s][task][run_name][dat_names[i]].append(dat[0][0][j+1][i][run][0][0])
#legible access to the data
Nline = 'NlineResults' #numberline

In [12]:
new_dat[sub_ex]['NlineResults']['run1'].keys()

[u'Slow',
 u'Line_pct',
 u'iti',
 u'TestX',
 u'ITI_onset_real',
 u'consider_onset_real',
 u'ITI_onset',
 u'RT',
 u'hold',
 u'decision_end',
 u'decision_onset_real',
 u'RTHold',
 u'decision_end_real',
 u'Correct',
 u'Wrong',
 u'BadPress',
 u'consider_onset',
 u'Response',
 u'Task',
 u'Trial',
 u'Points',
 u'Error',
 u'catch',
 u'mouse_pos',
 u'Block',
 u'catch_probe',
 u'Probe',
 u'hold_onset',
 u'Move',
 u'decision_onset',
 u'hold_onset_real',
 u'Click']

In [13]:
new_dat[sub_ex]['NlineResults']['run1']['Probe']

[array([57], dtype=uint8),
 array([77], dtype=uint8),
 array([3], dtype=uint8),
 array([21], dtype=uint8),
 array([60], dtype=uint8),
 array([28], dtype=uint8),
 array([85], dtype=uint8),
 array([74], dtype=uint8),
 array([33], dtype=uint8),
 array([7], dtype=uint8),
 array([90], dtype=uint8),
 array([36], dtype=uint8),
 array([11], dtype=uint8),
 array([45], dtype=uint8),
 array([98], dtype=uint8),
 array([65], dtype=uint8),
 array([70], dtype=uint8),
 array([14], dtype=uint8),
 array([80], dtype=uint8),
 array([20], dtype=uint8),
 array([-58], dtype=int16),
 array([-94], dtype=int16),
 array([-86], dtype=int16),
 array([54], dtype=uint8),
 array([-44], dtype=int16),
 array([-78], dtype=int16),
 array([-10], dtype=int16),
 array([48], dtype=uint8),
 array([30], dtype=uint8),
 array([-28], dtype=int16),
 array([96], dtype=uint8),
 array([-34], dtype=int16),
 u'of',
 u'is',
 u'be',
 u'me',
 u'it',
 u'as',
 u'my',
 u'so',
 u'we',
 u'or',
 u'ox',
 u'by',
 u'am',
 u'he',
 u'do',
 u'if']

In [76]:
new_dat[sub_ex]['NlineResults'].keys()

['run1', 'run3', 'run2', 'run4']

In [14]:
new_dat[sub_ex]['NlineResults']['run1']['catch_probe']

[array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), dtype=uint8),
 array([], shape=(0, 0), 

In [15]:
subj = data_dict.keys()
tasks = [Nline]
tuples = []
rows = len(data_dict[sub_ex]['p'][Nline][0][0][:])-1
for s in subj:
    runs = new_dat[s]['NlineResults'].keys()
    for run in runs:
        for i in range(0,rows):
            tuples.append((s, run, i))
len(tuples)
#iterables = [subj,tasks,runs]
indexes = pd.MultiIndex.from_tuples(tuples, names=['Subj', 'Run', 'Trial'])
nline_cols = len(new_dat[sub_ex][Nline]['run1'].keys())

In [77]:
indexes[590]

('s_02007', 'run1', 14)

In [17]:
indexes[1][1]

'run1'

In [18]:
varnames = new_dat[sub_ex][Nline]['run1'].keys()
varnames[24]

u'Block'

In [19]:
len(indexes)

4224

In [20]:
# Code empty cells of probes and catch_probes as Nan
Dic_list = []
probes = ['catch_probe']
for data in indexes:
    temp_dict = {}
    for var in varnames:
        if var == probes[0]:
            if len(new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]]) == 0:
                new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]] = np.array([np.nan])
            temp_dict[var] = new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]][0]
        else:
            temp_dict[var] = new_dat.get(data[0]).get(Nline).get(data[1]).get(var)[data[2]]
    Dic_list.append(temp_dict)

In [21]:
#Create dataframe
nline_df = pd.DataFrame(Dic_list, index=indexes)
sum(nline_df.loc[sub_ex].loc['run1'].iloc[0:48]['catch'])

12

In [22]:
nline_df.loc[sub_ex].loc['run1'].iloc[0:10]['Error']

Trial
0   -0.023744
1   -0.025507
2    0.000000
3    0.000000
4   -0.027313
5    0.001938
6   -0.046035
7    0.000000
8    0.070881
9    0.026916
Name: Error, dtype: float64

In [23]:
nline_df.index.names = ['Subject', 'Run', 'Trial']
nline_df.index.names

FrozenList([u'Subject', u'Run', u'Trial'])

In [28]:
test = nline_df['Probe']
for i in range(0,len(test)):
    test[i] = np.ravel(test[i])
    test[i] = test[i][0]
nline_df['Probe'] = test
nline_df['Probe']

/Users/frankanayet/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/frankanayet/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


Subject  Run   Trial
s_02009  run1  0         57
               1         77
               2          3
               3         21
               4         60
               5         28
               6         85
               7         74
               8         33
               9          7
               10        90
               11        36
               12        11
               13        45
               14        98
               15        65
               16        70
               17        14
               18        80
               19        20
               20       -58
               21       -94
               22       -86
               23        54
               24       -44
               25       -78
               26       -10
               27        48
               28        30
               29       -28
                       ... 
s_02022  run4  18        or
               19        my
               20        of
               21        we

### Create Stim Labels

In [29]:
#now nline
#nline_df['Num'] = nline_df['Num'].map('{:.0f}'.format)
#nline_df['Denom'] = nline_df['Denom'].map('{:.0f}'.format)
#nline_df['Stim'] = nline_df['Num']+'/'+nline_df['Denom']
#nline_df['Stim']

In [30]:
nline_df.columns

Index([           u'BadPress',               u'Block',               u'Click',
                   u'Correct',               u'Error',           u'ITI_onset',
            u'ITI_onset_real',            u'Line_pct',                u'Move',
                    u'Points',               u'Probe',                  u'RT',
                    u'RTHold',            u'Response',                u'Slow',
                      u'Task',               u'TestX',               u'Trial',
                     u'Wrong',               u'catch',         u'catch_probe',
            u'consider_onset', u'consider_onset_real',        u'decision_end',
         u'decision_end_real',      u'decision_onset', u'decision_onset_real',
                      u'hold',          u'hold_onset',     u'hold_onset_real',
                       u'iti',           u'mouse_pos'],
      dtype='object')

In [31]:
#Make task as string
nline_df['Task'] = nline_df['Task'].astype(str)
nline_df['Task'][nline_df['Task']=='1'] = 'Pos'
nline_df['Task'][nline_df['Task']=='2'] = 'Neg'
nline_df['Task'][nline_df['Task']=='3'] = 'Word'
nline_df['Task'].iloc[16]

/Users/frankanayet/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/frankanayet/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/frankanayet/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


'Neg'

In [32]:
nline_df['Dist0'] = abs(nline_df['Line_pct'] - 0)
nline_df['Dist100'] = abs(nline_df['Line_pct'] - 1)
nline_df['Dist50'] = abs(nline_df['Line_pct'] - 0.5)
nline_df['LandmarkDist'] = nline_df[['Dist0','Dist100','Dist50']].min(axis=1) 
nline_df['LandmarkDist']

Subject  Run   Trial
s_02009  run1  0        0.07
               1        0.23
               2        0.03
               3        0.21
               4        0.10
               5        0.22
               6        0.15
               7        0.24
               8        0.17
               9        0.07
               10       0.10
               11       0.14
               12       0.11
               13       0.05
               14       0.02
               15       0.15
               16       0.15
               17       0.07
               18       0.10
               19       0.10
               20       0.21
               21       0.03
               22       0.07
               23       0.23
               24       0.22
               25       0.11
               26       0.05
               27       0.24
               28       0.15
               29       0.14
                        ... 
s_02022  run4  18       0.15
               19       0.03
               20     

##Get means for demeaning

In [33]:
nline_df['LandmarkDist'] = np.round(nline_df['LandmarkDist'],2)
uniquevals = nline_df.loc['s_02007'].loc['run1']['LandmarkDist'].unique()
landmark_mean = uniquevals.mean()

In [34]:
nline_df['Dist50'] = np.round(nline_df['Dist50'],2)
uniquevals50 = nline_df.loc['s_02007'].loc['run1']['Dist50'].unique()
dist50_mean = uniquevals50.mean()

In [35]:
nline_df['Dist0'] = np.round(nline_df['Dist0'],2)
uniquevals0 = nline_df.loc['s_02007'].loc['run1']['Dist0'].unique()
dist0_mean = uniquevals0.mean()

In [36]:
dist0_mean

0.49375000000000002

# Create Onset Files

In [37]:
nline_df['Missed'] = 0

In [38]:
nline_df['Missed'][(nline_df.catch < 1) & (nline_df.Error == 1)] = 1

/Users/frankanayet/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [78]:
import string
tasks = nline_df.groupby('Task')
labels = tasks.indices.keys()
cons_trial_int = {}
dec_trial_int = {}

cons_land = {}
dec_land = {}
cons_zero = {}
dec_zero = {}
cons_mid = {}
dec_mid = {}

dec_ctch_onset = {}

# Breaks always happen at the same time in the sequence
break_onset = [[190, 6, 1],[388, 6, 1]]
for s in nline_df.index.levels[0]:
    print s
    cons_trial_int[s] = {}
    dec_trial_int[s] = {}
    
    cons_land[s] = {}
    dec_land[s] = {}
    cons_zero[s] = {}
    dec_zero[s] = {}
    cons_mid[s] = {}
    dec_mid[s] = {}

    dec_ctch_onset[s] = {}
    for r in nline_df.index.levels[1]:
        #print r
        ctch = nline_df.loc[s].loc[r]['catch']
        if len(nline_df.loc[s].loc[r]['hold']) == 0:
            hold = 2.5
        else:
            hold = min(nline_df.loc[s].loc[r]['hold'])
        probe = nline_df.loc[s].loc[r]['Line_pct']
        dec_ctch_tmp = nline_df.loc[s].loc[r]['decision_onset_real'] - 16
        dec_ctch_tmp = dec_ctch_tmp[ctch==1]
        dec_ctch_onset[s][r] = pd.DataFrame.from_items([('time',dec_ctch_tmp[dec_ctch_tmp>=0]),('duration',dec_time),('val',1)])
        
        cons_duration = hold + cons_time
        
        cons_trial_int[s][r] = {}
        dec_trial_int[s][r] = {}
        
        cons_land[s][r] = {}
        dec_land[s][r] = {}
        cons_zero[s][r] = {}
        dec_zero[s][r] = {}
        cons_mid[s][r] = {}
        dec_mid[s][r] = {}

        for lab in labels:
            #print lab
            Task = nline_df.loc[s].loc[r]['Task']
            #create landmark values (demeaned)
            landmark = nline_df.loc[s].loc[r]['LandmarkDist']
            landmark = landmark[Task==lab] - landmark_mean
            #create landmark values for distance from 50 (demeaned)
            dist50 = nline_df.loc[s].loc[r]['Dist50']
            dist50 = dist50[Task==lab] - dist50_mean
            #create landmark distance from 0
            dist0 = nline_df.loc[s].loc[r]['Dist0']
            dist0 = dist0[Task==lab] - dist0_mean
            # Intercept for consider phase
            tmp_int = nline_df.loc[s].loc[r]['consider_onset_real'] - 16
            tmp_int = tmp_int[Task==lab]
            #In this version Iam only using the duration of consider time + min(hold) and decision time
            #Instead of consider plus hold, and RT
            cons_trial_int[s][r][lab] = pd.DataFrame.from_items([('time',tmp_int[tmp_int>=0]),('duration',cons_duration),('val',1)])
            tmp_int = nline_df.loc[s].loc[r]['decision_onset_real'] - 16
            tmp_int = tmp_int[ctch==0]
            tmp_int = tmp_int[Task==lab]
            dec_trial_int[s][r][lab] = pd.DataFrame.from_items([('time',tmp_int[tmp_int>=0]),('duration',dec_time),('val',1)])
            #create time data for small and large numbers separetely
            cons_tmp = nline_df.loc[s].loc[r]['consider_onset_real'] - 16
            cons_tmp = cons_tmp[Task==lab]
            
            cons_land[s][r][lab] = pd.DataFrame.from_items([('time',cons_tmp[cons_tmp>=0]),('duration',cons_duration),('val',landmark)])        
            
            cons_zero[s][r][lab] = pd.DataFrame.from_items([('time',cons_tmp[cons_tmp>=0]),('duration',cons_duration),('val',dist0)])        
            
            cons_mid[s][r][lab] = pd.DataFrame.from_items([('time',cons_tmp[cons_tmp>=0]),('duration',cons_duration),('val',dist50)])        
            
            #Remove catch for decision phase
            landmark = landmark[ctch==0]
            dist50 = dist50[ctch==0]
            dist0 = dist0[ctch==0]
            #Now decision phase
            dec_tmp = nline_df.loc[s].loc[r]['decision_onset_real'] - 16
            dec_tmp = dec_tmp[ctch==0]
            dec_tmp = dec_tmp[Task==lab]
            
            dec_land[s][r][lab] = pd.DataFrame.from_items([('time',dec_tmp[dec_tmp>=0]),('duration',dec_time),('val',landmark)])        
            
            dec_zero[s][r][lab] = pd.DataFrame.from_items([('time',dec_tmp[dec_tmp>=0]),('duration',dec_time),('val',dist0)])        
            
            dec_mid[s][r][lab] = pd.DataFrame.from_items([('time',dec_tmp[dec_tmp>=0]),('duration',dec_time),('val',dist50)])        
            

s_02001
s_02002
s_02003
s_02004
s_02005
s_02006
s_02007
s_02009
s_02010
s_02011
s_02012
s_02014
s_02015
s_02016
s_02017
s_02018
s_02019
s_02020
s_02021
s_02022
s_02023
s_02024
s_02027


In [79]:
landmark_mean

0.13384615384615384

In [80]:
dec_trial_int['s_02009']['run1']

{'Neg':              time  duration  val
 Trial                           
 16     207.006346         3    1
 17     216.006646         3    1
 19     241.007333         3    1
 21     261.507806         3    1
 22     272.008154         3    1
 24     299.008807         3    1
 25     312.009198         3    1
 27     338.009907         3    1
 28     348.510182         3    1
 29     361.510471         3    1
 30     372.010803         3    1
 31     385.011124         3    1, 'Pos':              time  duration  val
 Trial                           
 0        5.501116         3    1
 1       15.001360         3    1
 4       52.002189         3    1
 5       65.502652         3    1
 6       77.002845         3    1
 8      102.003595         3    1
 9      113.003934         3    1
 10     123.504180         3    1
 11     137.504582         3    1
 12     149.004902         3    1
 14     175.505432         3    1
 15     187.005909         3    1, 'Word':              time  durati

In [82]:
dec_land['s_02003']['run1']

{'Neg':              time  duration       val
 Trial                                
 0        6.012702         3  0.106154
 1       19.020832         3  0.076154
 2       30.502330         3 -0.103846
 5       66.031017         3 -0.063846
 6       76.503249         3  0.016154
 8      104.532092         3 -0.083846
 10     130.004121         3  0.006154
 11     141.016508         3  0.096154
 12     153.008933         3  0.086154
 13     166.000410         3  0.016154
 14     176.017658         3 -0.033846
 15     187.004192         3 -0.113846,
 'Pos':              time  duration       val
 Trial                                
 16     204.001585         3  0.006154
 17     216.018680         3  0.036154
 18     228.018982         3  0.086154
 21     261.503145         3  0.096154
 22     272.003427         3 -0.103846
 23     285.020404         3  0.016154
 25     311.504676         3 -0.033846
 26     322.521748         3 -0.063846
 27     332.527450         3  0.106154
 28     34

## Save Files

In [83]:
tasks = {'Pos': [cons_trial_int, dec_trial_int, cons_land, dec_land, cons_zero, dec_zero, cons_mid,
                 dec_mid],
         'Neg': [cons_trial_int, dec_trial_int, cons_land, dec_land, cons_zero, dec_zero, cons_mid,
                 dec_mid],
         'Word': [cons_trial_int, dec_trial_int, cons_land, dec_land, cons_zero, dec_zero, cons_mid,
                 dec_mid]}

taskname = ['cons_trial_int', 'dec_trial_int', 'cons_land', 'dec_land', 'cons_zero', 'dec_zero', 'cons_mid',
            'dec_mid']
        
runs = ['run1', 'run2', 'run3', 'run4']

for s in nline_df.index.levels[0]:
    print s
    #Laptop
    #path = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LandmarksFull'
    #path = '/Users/frankkanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LandmarksFull/'+s+'/'
    #Desktop
    path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LandmarksFull4'
    path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LandmarksFull4/'+s+'/'
    os.makedirs(path)
    for r in nline_df.index.levels[1]:
        print r
        dec_ctch_filename = s+'_'+r+'_DEC_CTCH'+'.txt'
        dec_ctch_pathfile = path+dec_ctch_filename
        dec_ctch_onset[s][r].to_csv(dec_ctch_pathfile, sep='\t', header=False, index=False)
        for task in tasks.keys():
            print task
            for name in range(0,len(tasks[task])):
                filename = s+'_'+task+'_'+r+'_'+taskname[name]+'.txt'
                pathfile = path+filename
                tasks[task][name][s][r][task].to_csv(pathfile, sep='\t', header=False, index=False)
                
            
            #dec_small_filename = s+'_'+task+'_'+r+'_'+'DEC_SM'+'.txt'
            #cons_small_filename = s+'_'+task+'_'+r+'_'+'CONS_SM'+'.txt'
            #dec_large_filename = s+'_'+task+'_'+r+'_'+'DEC_LG'+'.txt'
            #cons_large_filename = s+'_'+task+'_'+r+'_'+'CONS_LG'+'.txt'
            #dec_int_pathfile = path+dec_int_filename
            #cons_int_pathfile = path+cons_int_filename
            #dec_small_pathfile = path+dec_small_filename
            #cons_small_pathfile = path+cons_small_filename
            #dec_large_pathfile = path+dec_large_filename
            #cons_large_pathfile = path+cons_large_filename
            #tasks[task][0][s][r][task].to_csv(cons_int_pathfile, sep='\t', header=False, index=False)
            #tasks[task][1][s][r][task].to_csv(dec_int_pathfile, sep='\t', header=False, index=False)
            #tasks[task][2][s][r][task].to_csv(cons_small_pathfile, sep='\t', header=False, index=False)
            #tasks[task][3][s][r][task].to_csv(dec_small_pathfile, sep='\t', header=False, index=False)
            #tasks[task][4][s][r][task].to_csv(cons_large_pathfile, sep='\t', header=False, index=False)
            #tasks[task][5][s][r][task].to_csv(dec_large_pathfile, sep='\t', header=False, index=False)

s_02001
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02002
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02003
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02004
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02005
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02006
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02007
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02009
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02010
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02011
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02012
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02014
run1
Neg
Word
Pos
run2
Neg
Word
Pos
run3
Neg
Word
Pos
run4
Neg
Word
Pos
s_02015
run1
Neg
Word
Pos
run2
Neg
Word


In [84]:
len(tasks['Word'])

8

In [85]:
#Save Break onset file
path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/OnsetFiles_LandmarksFull4/'
#Desktop
break_onset = pd.DataFrame.from_items([('time',[190, 388]),('duration',[6,6]),('val',[1,1])])
break_filename = 'Break_onsets.txt'
break_pathfile = path+break_filename
break_onset.to_csv(break_pathfile, sep='\t', header=False, index=False)